-- Update data for Australia country
UPDATE countries
SET
  -- Basic Information
  capital = 'Canberra',
  population = '25.7 million (2021)',
  language = 'English',
  currency = 'Australian Dollar (AUD)',
  academic_year = 'February to November',
  education_system = 'Australian Qualifications Framework (AQF)',
  
  -- Education Statistics
  international_students = '600,000+',
  top_universities = '39 universities in global top 500',
  english_programs = '22,000+ programs taught in English',
  post_study_work = 'Up to 4 years (Post-Study Work visa)',
  
  -- Education System
  bachelor_info = 'Usually 3 years (some professional programs like engineering or law take 4-5 years). Programs focus on both theoretical knowledge and practical skills development, with emphasis on critical thinking and independent research.',
  master_info = 'Usually 1-2 years. Two main types: coursework masters (focused on advanced professional skills) and research masters (emphasis on original research and a thesis).',
  phd_info = 'Usually 3-4 years. Research-focused with a significant original contribution to the field. Many programs include coursework components and teaching opportunities.',
  teaching_style = 'Interactive and student-centered with emphasis on critical thinking, discussion, and practical application. Features tutorials, workshops, laboratory sessions, and field work alongside lectures.',
  grading_system = 'High Distinction (HD, 85-100%), Distinction (D, 75-84%), Credit (CR, 65-74%), Pass (P, 50-64%), Fail (F, below 50%). Some universities use slightly different scales.',
  instruction_language = 'English is the primary language of instruction across all institutions and programs.',
  academic_calendar = 'Two semesters: Semester 1 (February to June) and Semester 2 (July to November). Some universities operate on a trimester system with three teaching periods per year.',
  universities_intro = 'Australia has 43 universities, including research-intensive "Group of Eight" institutions, innovative technology-focused universities, and regional campuses specializing in specific fields. Australian qualifications are globally recognized for their high quality and practical approach.',
  
  -- Admission & Visa Requirements
  educational_requirements = 'Completed secondary education equivalent to Australian Year 12 for undergraduate studies. For master''s programs, a relevant bachelor''s degree is required, with specific grade requirements depending on the program.',
  transcript_requirements = 'Official academic transcripts from all previous educational institutions, with certified English translations if originals are not in English.',
  entrance_exams = 'Not generally required for most programs. Some professional courses may require specific tests. Graduate Management Admission Test (GMAT) or Graduate Record Examinations (GRE) may be required for certain business or graduate programs.',
  english_requirements = 'IELTS: typically 6.0-7.0 overall (minimum 6.0 in each band) for undergraduate, 6.5-7.5 for postgraduate. TOEFL: 60-100 iBT depending on the program and university. PTE Academic and Cambridge English also accepted.',
  language_exemptions = 'Students who have completed substantial education (at least 2-5 years) in an English-speaking country or institution may be exempt from language tests.',
  visa_requirements = 'All international students need a Student visa (subclass 500). Must be enrolled in a registered course, meet health and character requirements, and demonstrate genuine temporary entrant status.',
  financial_requirements = 'Proof of sufficient funds to cover tuition, living expenses, and travel costs (approximately AUD 21,041 per year plus tuition fees). Evidence can include bank statements, scholarships, or sponsorship letters.',
  health_requirements = 'Overseas Student Health Cover (OSHC) is mandatory for the entire duration of stay in Australia, except for students from countries with reciprocal healthcare agreements.',
  additional_documents = 'Valid passport, letter of offer from an Australian institution, Confirmation of Enrollment (CoE), statement of purpose, passport-sized photographs, and health examination results if required.',
  visa_tip = 'Lodge your visa application at least 6-8 weeks before your course start date. Be transparent about your circumstances and genuine intent to study, as Australian visa officials thoroughly assess all applications.',
  
  -- Tuition & Living Costs
  bachelor_fee_public = 'AUD 20,000 - 45,000 per year',
  bachelor_fee_private = 'AUD 25,000 - 50,000 per year',
  bachelor_fee_medical = 'AUD 60,000 - 80,000 per year',
  master_fee_public = 'AUD 22,000 - 50,000 per year',
  master_fee_private = 'AUD 25,000 - 60,000 per year',
  master_fee_business = 'AUD 35,000 - 80,000 per program',
  accommodation_cost = 'AUD 150 - 700 per week',
  accommodation_note = 'University accommodation costs AUD 150-400/week. Private rentals range from AUD 200-700/week depending on location and type. Homestay options cost around AUD 250-350/week.',
  food_cost = 'AUD 100 - 200 per week',
  food_note = 'Cooking at home costs around AUD 80-100/week for basic groceries. Eating out costs approximately AUD 15-30 per meal in affordable restaurants.',
  transport_cost = 'AUD 30 - 60 per week',
  transport_note = 'Public transport concessions are available for international students in some states. Weekly passes cost around AUD 30-60 depending on the city and distance.',
  utilities_cost = 'AUD 50 - 100 per week',
  utilities_note = 'Includes electricity, gas, water, and internet. Often partially included in university accommodation fees.',
  other_cost = 'AUD 80 - 150 per week',
  other_note = 'Includes phone plans, entertainment, books, and personal expenses.',
  total_monthly_cost = 'AUD 1,700 - 2,800 per month',
  budget_tip1 = 'Consider living in suburbs further from city centers to save on rent, especially in Sydney and Melbourne which have higher costs.',
  budget_tip2 = 'Take advantage of student discounts available with your student ID for transportation, entertainment, and retail purchases.',
  budget_tip3 = 'Use university facilities like libraries, gyms, and computer labs to reduce personal expenses for these services.',
  budget_tip4 = 'International students can work up to 48 hours per fortnight during term and unlimited hours during scheduled breaks to supplement income.',
  government_scholarships = 'Australia Awards, Research Training Program (RTP), and Destination Australia scholarships provide substantial funding for international students at various levels.',
  university_scholarships = 'Most Australian universities offer merit-based scholarships for international students, covering partial or full tuition fees based on academic excellence.',
  external_scholarships = 'Endeavour Scholarships, country-specific scholarships from home governments, and industry-sponsored scholarships provide additional funding opportunities.',
  
  -- Student Life
  campus_life = 'Australian campuses feature modern facilities, libraries, research centers, sports complexes, and vibrant student hubs with cafes, shops, and social spaces.',
  campus_life_extra = 'Universities host orientation weeks, cultural events, sports competitions, and clubs covering diverse interests from academics to hobbies, arts, and social causes.',
  work_opportunities = 'International students can work up to 48 hours per fortnight during term time and unlimited hours during scheduled breaks. Post-Study Work visas allow graduates to work for 2-4 years after completion.',
  work_opportunities_extra = 'Part-time work is widely available in retail, hospitality, and administrative roles. Professional opportunities through internships and industry placements are often integrated into degree programs.',
  cultural_experience = 'Australia offers diverse experiences from vibrant multicultural cities to unique natural environments including beaches, rainforests, and the Outback.',
  cultural_experience_extra = 'The country embraces multiculturalism with over 200 ethnicities represented in its population. Students can experience Indigenous culture, arts festivals, sporting events, and a relaxed, outdoor lifestyle.',
  student_life_image1 = '/images/placeholders/student-life-1.jpg',
  student_life_image2 = '/images/placeholders/student-life-2.jpg',
  student_life_image3 = '/images/placeholders/student-life-3.jpg',
  student_life_image4 = '/images/placeholders/student-life-4.jpg',
  
  -- Testimonials
  testimonial1_name = 'Ravi Patel',
  testimonial1_image = '/images/placeholders/testimonial-1.jpg',
  testimonial1_program = 'Master of Engineering',
  testimonial1_university = 'University of Melbourne',
  testimonial1_quote = 'Studying in Australia has given me access to cutting-edge research facilities and industry connections that have been invaluable for my career development. Melbourne''s diverse culture and vibrant student community made settling in easy, despite being so far from home.',
  testimonial1_country = 'From India',
  testimonial2_name = 'Liu Wei',
  testimonial2_image = '/images/placeholders/testimonial-2.jpg',
  testimonial2_program = 'Bachelor of Business',
  testimonial2_university = 'University of Sydney',
  testimonial2_quote = 'The practical approach to learning in my business program has been excellent, with real-world case studies and internship opportunities. Sydney is a beautiful city with amazing beaches and outdoor activities. The work-life balance in Australia is something I''ve really come to appreciate.',
  testimonial2_country = 'From China',
  testimonial3_name = 'Maria Rodriguez',
  testimonial3_image = '/images/placeholders/testimonial-3.jpg',
  testimonial3_program = 'PhD in Marine Biology',
  testimonial3_university = 'James Cook University',
  testimonial3_quote = 'Australia was the obvious choice for my marine biology research. The Great Barrier Reef is literally my laboratory! The research support and collaborative environment at JCU have helped me connect with leading experts in my field and publish my work internationally.',
  testimonial3_country = 'From Colombia',
  
  -- FAQs
  faq1_question = 'What are the benefits of studying in Australia?',
  faq1_answer = 'Australia offers world-class education, globally recognized qualifications, a safe and welcoming multicultural environment, excellent quality of life, diverse landscapes and experiences, strong student support services, work rights during and after study, and potential pathways to permanent residency.',
  faq2_question = 'How much does it cost to study and live in Australia?',
  faq2_answer = 'Tuition fees range from AUD 20,000-80,000 per year depending on the program and institution. Living expenses typically amount to AUD 21,000-33,000 per year including accommodation, food, transport, and other personal expenses. Costs are higher in major cities like Sydney and Melbourne.',
  faq3_question = 'What are the work opportunities for international students?',
  faq3_answer = 'During studies, students can work up to 48 hours per fortnight while courses are in session and unlimited hours during scheduled breaks. After graduation, the Post-Study Work visa allows graduates to work for 2-4 years depending on the qualification level and location of study.',
  faq4_question = 'What are the visa requirements for studying in Australia?',
  faq4_answer = 'Students need a Student visa (subclass 500), requiring acceptance into a registered course, sufficient funds for tuition and living expenses, adequate health insurance (OSHC), English proficiency, and meeting health and character requirements.',
  faq5_question = 'Are there scholarships available for international students?',
  faq5_answer = 'Yes, scholarships are available through the Australian government (Australia Awards, RTP, Destination Australia), individual universities, and external organizations. Most are merit-based and highly competitive, so early research and application is recommended.',
  faq6_question = 'What accommodation options are available for students?',
  faq6_answer = 'Options include on-campus university colleges or halls of residence, purpose-built student apartments, homestays with local families, shared rentals, and private apartments. University accommodation is a good starting option for first-year students as it provides community and support.',
  faq7_question = 'What healthcare provisions are there for international students?',
  faq7_answer = 'Overseas Student Health Cover (OSHC) is mandatory and provides basic medical and hospital care, pharmaceuticals, and ambulance services. Additional private health insurance can cover extra services like dental and optical care. Some universities have on-campus health services.',
  faq8_question = 'Can studying in Australia lead to permanent residency?',
  faq8_answer = 'Yes, studying in Australia can provide pathways to permanent residency through the skilled migration program. Qualifying Australian qualifications, work experience gained on a Post-Study Work visa, and skills in demand can contribute to eligibility for various visa options leading to permanent residency.'
WHERE slug = 'australia'; 