-- Update data for Canada country
UPDATE countries
SET
  -- Basic Information
  capital = 'Ottawa',
  population = '38.2 million (2021)',
  language = 'English and French (official)',
  currency = 'Canadian Dollar (CAD)',
  academic_year = 'September to April',
  education_system = 'Credit-based system similar to the US',
  
  -- Education Statistics
  international_students = '640,000+',
  top_universities = '30 universities in global top 500',
  english_programs = '15,000+ programs taught in English',
  post_study_work = 'Up to 3 years (Post-Graduation Work Permit)',
  
  -- Education System
  bachelor_info = 'Usually 4 years (3 years in Quebec). Programs combine major-specific courses with electives and general education requirements, offering flexibility and interdisciplinary learning.',
  master_info = 'Usually 1-2 years. Programs can be course-based, research-based, or a combination. Many include co-op options for work experience.',
  phd_info = 'Usually 4-6 years. Research-focused with coursework components. Often includes teaching opportunities and funding packages.',
  teaching_style = 'Interactive and student-centered approach with emphasis on critical thinking, group discussions, and practical applications. Smaller class sizes and direct access to professors are common.',
  grading_system = 'A+ to F letter grade system, typically with A+ (90-100%), A (85-89%), A- (80-84%), B+ (77-79%), etc. GPA is usually calculated on a 4.0 or 4.3 scale.',
  instruction_language = 'English is the primary language of instruction, except in Quebec where many institutions teach in French. Bilingual programs are available in some universities.',
  academic_calendar = 'Two main semesters: Fall (September-December) and Winter (January-April), with optional Summer term (May-August). Some universities use trimester systems.',
  universities_intro = 'Canada has 96 universities, including comprehensive research institutions and specialized colleges. Canadian universities are known for their high-quality education, modern facilities, and cutting-edge research.',
  
  -- Admission & Visa Requirements
  educational_requirements = 'Completed secondary education equivalent to Canadian high school diploma. For master''s programs, a relevant bachelor''s degree is required with competitive GPA (typically 3.0/4.0 or higher).',
  transcript_requirements = 'Official transcripts from all previous educational institutions, translated to English or French if necessary and often evaluated by a recognized credential evaluation service.',
  entrance_exams = 'Undergraduate: SAT/ACT may be required by some universities (but often waived for international applicants). Graduate: GRE/GMAT for specific programs (especially business and STEM).',
  english_requirements = 'IELTS: typically 6.5 overall (minimum 6.0 in each band) for undergraduate, 6.5-7.0 for graduate. TOEFL: 80-100 iBT, depending on the program and university.',
  language_exemptions = 'Students from countries where English is the primary language of instruction may be exempt from language tests. Some French-speaking universities accept DELF/DALF for French proficiency.',
  visa_requirements = 'International students need a study permit to study courses longer than 6 months. This serves as a student visa and is tied to acceptance at a Designated Learning Institution (DLI).',
  financial_requirements = 'Proof of sufficient funds to cover tuition and living expenses (approximately CAD 10,000 per year plus tuition fees, or about CAD 20,000-25,000 total per year).',
  health_requirements = 'Medical examination may be required depending on country of origin. Health insurance is mandatory and provided by provinces or universities.',
  additional_documents = 'Letter of acceptance from a Canadian DLI, valid passport, statement of purpose, proof of ties to home country, biometric data collection for many countries.',
  visa_tip = 'Apply for your study permit as soon as you receive your university acceptance, as processing can take 4-16 weeks depending on your country. Be sure to use the official IRCC website or verified representatives.',
  
  -- Tuition & Living Costs
  bachelor_fee_public = 'CAD 20,000 - 40,000 per year',
  bachelor_fee_private = 'CAD 25,000 - 50,000 per year',
  bachelor_fee_medical = 'CAD 25,000 - 65,000 per year',
  master_fee_public = 'CAD 12,000 - 35,000 per year',
  master_fee_private = 'CAD 20,000 - 50,000 per year',
  master_fee_business = 'CAD 30,000 - 80,000 per program',
  accommodation_cost = 'CAD 600 - 1,500 per month',
  accommodation_note = 'University residence halls cost CAD 5,000-11,000 per academic year. Off-campus shared housing ranges from CAD 600-1,200/month, with higher costs in major cities like Toronto and Vancouver.',
  food_cost = 'CAD 400 - 600 per month',
  food_note = 'University meal plans cost about CAD 3,000-5,000 per academic year. Grocery shopping amounts to approximately CAD 300-400/month for basic necessities.',
  transport_cost = 'CAD 80 - 150 per month',
  transport_note = 'Public transportation passes with student discounts cost CAD 80-120/month depending on the city. Many universities include transit passes in student fees.',
  utilities_cost = 'CAD 100 - 200 per month',
  utilities_note = 'Includes electricity, heating, water, and internet. Often included in university residence fees but additional for off-campus housing.',
  other_cost = 'CAD 200 - 400 per month',
  other_note = 'Includes phone plan (CAD 50-80), books and supplies (CAD 500-1,000 per year), clothing, entertainment, and personal items.',
  total_monthly_cost = 'CAD 1,380 - 2,850 per month',
  budget_tip1 = 'Consider university housing for your first year as it''s convenient and often includes meal plans and utilities.',
  budget_tip2 = 'Apply for on-campus jobs (allowed to work up to 20 hours per week during studies) to supplement your income.',
  budget_tip3 = 'Open a Canadian bank account with student packages that often waive monthly fees and provide additional benefits.',
  budget_tip4 = 'Use your student ID for discounts on transportation, entertainment, dining, and shopping across Canada.',
  government_scholarships = 'The Canadian government offers various scholarships including the Vanier Canada Graduate Scholarships, Banting Postdoctoral Fellowships, and Canada Graduate Scholarships.',
  university_scholarships = 'Most Canadian universities offer entrance scholarships and awards specifically for international students based on academic excellence.',
  external_scholarships = 'Organizations like the Canadian Bureau for International Education (CBIE), provincial governments, and country-specific funding bodies offer scholarships for international students.',
  
  -- Student Life
  campus_life = 'Canadian universities offer vibrant campus communities with modern facilities, student centers, libraries, sports complexes, and diverse student clubs and organizations.',
  campus_life_extra = 'Campus events throughout the year include orientation week, homecoming, cultural festivals, concerts, and sporting events that foster community engagement and school spirit.',
  work_opportunities = 'International students can work up to 20 hours per week during academic sessions and full-time during scheduled breaks without a separate work permit.',
  work_opportunities_extra = 'After graduation, the Post-Graduation Work Permit Program (PGWPP) allows graduates to work in Canada for up to 3 years, depending on the length of their study program.',
  cultural_experience = 'Canada is known for its multiculturalism, diverse communities, and inclusive environment. Students can experience different cultures, cuisines, festivals, and traditions throughout the country.',
  cultural_experience_extra = 'From vibrant cities to stunning natural landscapes, Canada offers diverse environments for exploration including mountains, lakes, forests, and coastlines, with activities available in all four distinct seasons.',
  student_life_image1 = '/images/placeholders/student-life-1.jpg',
  student_life_image2 = '/images/placeholders/student-life-2.jpg',
  student_life_image3 = '/images/placeholders/student-life-3.jpg',
  student_life_image4 = '/images/placeholders/student-life-4.jpg',
  
  -- Testimonials
  testimonial1_name = 'Rahul Patel',
  testimonial1_image = '/images/placeholders/testimonial-1.jpg',
  testimonial1_program = 'MSc in Computer Science',
  testimonial1_university = 'University of Toronto',
  testimonial1_quote = 'The quality of education and research opportunities at UofT are exceptional. What I value most is the collaborative environment and the chance to work with leading researchers in my field. The career support services have also helped me connect with tech companies in the Toronto-Waterloo corridor.',
  testimonial1_country = 'From India',
  testimonial2_name = 'Sofia Martinez',
  testimonial2_image = '/images/placeholders/testimonial-2.jpg',
  testimonial2_program = 'BA in Environmental Studies',
  testimonial2_university = 'University of British Columbia',
  testimonial2_quote = 'Studying in Vancouver has been incredible - I''m surrounded by mountains, ocean, and forests, which is perfect for my environmental studies program. The multicultural community at UBC has expanded my perspective, and the emphasis on sustainability aligns perfectly with my values.',
  testimonial2_country = 'From Colombia',
  testimonial3_name = 'Ahmed Hassan',
  testimonial3_image = '/images/placeholders/testimonial-3.jpg',
  testimonial3_program = 'MBA',
  testimonial3_university = 'McGill University',
  testimonial3_quote = 'McGill''s MBA program has exceeded my expectations with its focus on practical learning and global business perspectives. Montreal offers a fantastic blend of North American and European culture. The networking opportunities and industry connections have been invaluable for my career goals.',
  testimonial3_country = 'From Egypt',
  
  -- FAQs
  faq1_question = 'What are the benefits of studying in Canada?',
  faq1_answer = 'Canada offers high-quality education with globally recognized credentials, a safe and welcoming environment for international students, cultural diversity, numerous research opportunities, and excellent post-graduation work options with pathways to permanent residency.',
  faq2_question = 'How much does it cost to study and live in Canada?',
  faq2_answer = 'International student tuition ranges from CAD 20,000-65,000 per year depending on the program and institution. Living expenses typically amount to CAD 15,000-35,000 per year, with higher costs in major cities like Toronto, Vancouver, and Montreal.',
  faq3_question = 'Do I need to speak French to study in Canada?',
  faq3_answer = 'No, English is the primary language of instruction at most Canadian universities except in Quebec, where many institutions teach in French. However, there are English-language universities in Quebec (like McGill and Concordia) and bilingual institutions throughout Canada.',
  faq4_question = 'Can I work while studying in Canada?',
  faq4_answer = 'Yes, international students can work up to 20 hours per week during academic sessions and full-time during scheduled breaks without needing a separate work permit, as long as they have a valid study permit and are enrolled full-time at a designated learning institution.',
  faq5_question = 'What are the visa requirements for studying in Canada?',
  faq5_answer = 'You need a study permit to study in Canada for programs longer than 6 months. Requirements include acceptance from a designated learning institution, proof of financial support, clean criminal record, good health, and intent to leave Canada after studies (though pathways to permanent residency exist).',
  faq6_question = 'Are there scholarships available for international students?',
  faq6_answer = 'Yes, international students can access various scholarships through the Canadian government, individual universities, private organizations, and home country funding sources. These include merit-based entrance scholarships, research grants, and awards for specific fields of study.',
  faq7_question = 'What healthcare provisions are there for international students?',
  faq7_answer = 'International students in most provinces can access provincial healthcare plans (like OHIP in Ontario or MSP in British Columbia) after a waiting period. Some provinces require private health insurance, which is often arranged through universities. Coverage is comprehensive and affordable.',
  faq8_question = 'What are the post-graduation work options in Canada?',
  faq8_answer = 'Graduates from eligible Canadian institutions can apply for the Post-Graduation Work Permit (PGWP), allowing them to work in Canada for up to 3 years, depending on their program length. This provides valuable Canadian work experience and can lead to permanent residency through Express Entry or Provincial Nominee Programs.'
WHERE slug = 'canada'; 