-- Update data for Germany country
UPDATE countries
SET
  -- Basic Information
  capital = 'Berlin',
  population = '83.2 million (2021)',
  language = 'German',
  currency = 'Euro (€)',
  academic_year = 'October to September',
  education_system = 'European Credit Transfer System (ECTS)',
  
  -- Education Statistics
  international_students = '416,000+',
  top_universities = '45 universities in global top 500',
  english_programs = '1,700+ programs taught in English',
  post_study_work = 'Up to 18 months',
  
  -- Education System
  bachelor_info = 'Usually 3-4 years (180-240 ECTS). Combines theoretical coursework with practical applications. Programs can be more academic (Universitäten) or more application-oriented (Fachhochschulen).',
  master_info = 'Usually 1-2 years (60-120 ECTS). Highly specialized programs that build on bachelor''s knowledge and often include research components.',
  phd_info = 'Usually 3-5 years. Two main paths: traditional individual doctorate with a supervisor or structured doctoral program with coursework and research.',
  teaching_style = 'Emphasizes independent learning, critical thinking, and research skills. Students are expected to take initiative in their studies and participate actively in discussions.',
  grading_system = '1.0-1.5 (Very Good), 1.6-2.5 (Good), 2.6-3.5 (Satisfactory), 3.6-4.0 (Sufficient), > 4.0 (Fail). The lower the number, the better the grade.',
  instruction_language = 'German is the main language of instruction, but there are numerous programs taught entirely in English, especially at the master''s and PhD levels.',
  academic_calendar = 'Two semesters: Winter semester (October to March) and Summer semester (April to September). Lectures typically end earlier, followed by an examination period.',
  universities_intro = 'Germany has over 400 state-accredited universities including traditional research universities (Universitäten), universities of applied sciences (Fachhochschulen), and colleges of art, film, and music.',
  
  -- Admission & Visa Requirements
  educational_requirements = 'For Bachelor''s: Higher secondary school certificate equivalent to the German Abitur. For Master''s: A relevant bachelor''s degree with good academic standing.',
  transcript_requirements = 'Official transcripts and degree certificates with their certified translations in German or English.',
  entrance_exams = 'TestAS (Scholastic Aptitude Test) may be required for some programs. Artistic programs often require portfolio submissions or entrance tests.',
  english_requirements = 'For English-taught programs: IELTS (6.0-6.5), TOEFL (80-90 iBT), or Cambridge English certificates, depending on the institution and program level.',
  language_exemptions = 'Native English speakers or those who completed previous education in English may be exempt from language tests for English-taught programs.',
  visa_requirements = 'Non-EU/EEA students need a national visa (D-visa) for study purposes, followed by a residence permit once in Germany.',
  financial_requirements = 'Proof of financial resources of approximately €10,332 per year (can be through blocked account, scholarship, or sponsor''s financial guarantee).',
  health_requirements = 'Health insurance is mandatory for all students. Public health insurance costs about €110 per month for students under 30.',
  additional_documents = 'Valid passport, acceptance letter from a German university, proof of German language skills (for German-taught programs), biometric photos.',
  visa_tip = 'Apply for your student visa at least 3 months before your planned departure, as processing can take 4-6 weeks or longer during peak periods.',
  
  -- Tuition & Living Costs
  bachelor_fee_public = 'No tuition fees in most federal states (only semester contribution of €150-350)',
  bachelor_fee_private = '€6,000 - €20,000 per year',
  bachelor_fee_medical = '€1,500 - €5,000 per semester (public universities), €20,000+ per year (private)',
  master_fee_public = 'Mostly free (some federal states charge €1,500 - €3,000 per semester for non-EU students)',
  master_fee_private = '€8,000 - €30,000 per year',
  master_fee_business = '€15,000 - €40,000 per program',
  accommodation_cost = '€300 - €700 per month',
  accommodation_note = 'Student dormitories (€250-350/month) are the most affordable option. Private rooms in shared apartments (WG) cost €300-500/month, while private apartments range from €500-800/month depending on the city.',
  food_cost = '€170 - €250 per month',
  food_note = 'University canteens (Mensa) offer affordable meals (€3-5). Grocery shopping costs around €170-200/month for basic necessities.',
  transport_cost = '€70 - €100 per month',
  transport_note = 'Semester ticket for public transport is included in the semester contribution at most universities, providing unlimited travel within the city/region.',
  utilities_cost = '€80 - €150 per month',
  utilities_note = 'Includes electricity, heating, water, and internet. Often partially included in dormitory fees.',
  other_cost = '€100 - €200 per month',
  other_note = 'Includes books, leisure activities, phone plans, and health insurance (if above 30 years or for private insurance).',
  total_monthly_cost = '€720 - €1,400 per month',
  budget_tip1 = 'Open a German bank account to avoid foreign transaction fees and facilitate rent payments and other transactions.',
  budget_tip2 = 'Apply early for student dormitories as they are the most affordable accommodation option but have limited spaces.',
  budget_tip3 = 'Take advantage of student discounts for museums, theaters, cinemas, and other cultural establishments with your student ID.',
  budget_tip4 = 'Use university facilities like libraries, gyms, and computer labs to reduce personal expenses for these services.',
  government_scholarships = 'DAAD (German Academic Exchange Service) offers numerous scholarships for international students at all academic levels.',
  university_scholarships = 'Many German universities offer merit-based scholarships, Deutschland Stipendium (€300/month), and other funding opportunities for international students.',
  external_scholarships = 'Various foundations (e.g., Heinrich Böll, Friedrich Ebert, Konrad Adenauer) and country-specific organizations provide scholarships for study in Germany.',
  
  -- Student Life
  campus_life = 'German universities typically don''t have traditional enclosed campuses but are integrated into the city. Student life centers around academic buildings, libraries, and social venues across the city.',
  campus_life_extra = 'Student organizations (Fachschaften) and university groups organize events, parties, excursions, and support services for both academic and social aspects of university life.',
  work_opportunities = 'International students can work up to 120 full days or 240 half days per year without requiring an additional work permit.',
  work_opportunities_extra = 'After graduation, international students can extend their residence permit for up to 18 months to seek employment related to their studies. Jobs in engineering, IT, and other STEM fields are particularly abundant.',
  cultural_experience = 'Germany offers rich cultural experiences with its historical sites, museums, music festivals, and diverse regional traditions. Each region has its unique customs, cuisine, and dialects to explore.',
  cultural_experience_extra = 'The country''s central location in Europe makes it ideal for traveling to neighboring countries. Excellent public transportation systems make it easy to explore Germany and beyond.',
  student_life_image1 = '/images/placeholders/student-life-1.jpg',
  student_life_image2 = '/images/placeholders/student-life-2.jpg',
  student_life_image3 = '/images/placeholders/student-life-3.jpg',
  student_life_image4 = '/images/placeholders/student-life-4.jpg',
  
  -- Testimonials
  testimonial1_name = 'Priya Sharma',
  testimonial1_image = '/images/placeholders/testimonial-1.jpg',
  testimonial1_program = 'MSc in Mechanical Engineering',
  testimonial1_university = 'Technical University of Munich',
  testimonial1_quote = 'The quality of education in Germany is exceptional, especially in engineering. The program''s strong focus on practical applications and industry connections helped me secure an internship at BMW. The best part? No tuition fees!',
  testimonial1_country = 'From India',
  testimonial2_name = 'Carlos Mendes',
  testimonial2_image = '/images/placeholders/testimonial-2.jpg',
  testimonial2_program = 'BA in International Business',
  testimonial2_university = 'University of Mannheim',
  testimonial2_quote = 'Studying in Germany has given me a truly international perspective. The diverse student body and the emphasis on critical thinking have transformed my approach to business. The affordable living costs compared to other European countries is a significant advantage.',
  testimonial2_country = 'From Brazil',
  testimonial3_name = 'Min-Ji Park',
  testimonial3_image = '/images/placeholders/testimonial-3.jpg',
  testimonial3_program = 'PhD in Computer Science',
  testimonial3_university = 'Humboldt University of Berlin',
  testimonial3_quote = 'The research environment in Germany is extremely supportive and well-funded. My program offers me access to cutting-edge technology and regular opportunities to present at international conferences. Berlin''s tech scene is also fantastic for networking.',
  testimonial3_country = 'From South Korea',
  
  -- FAQs
  faq1_question = 'What are the benefits of studying in Germany?',
  faq1_answer = 'Major benefits include free or low-cost tuition at public universities, internationally recognized degrees, high-quality education with modern facilities, strong industry connections, diverse international environment, and good post-study work options (up to 18 months).',
  faq2_question = 'How much does it cost to study and live in Germany?',
  faq2_answer = 'Public universities charge no tuition fees in most federal states (only semester fees of €150-350). Private universities cost €6,000-40,000 per year. Living expenses range from €720-1,400 per month depending on the city, with smaller cities being more affordable than Munich or Frankfurt.',
  faq3_question = 'Do I need to speak German to study in Germany?',
  faq3_answer = 'Not necessarily. While German programs require German language proficiency (usually B2/C1 level), there are over 1,700 programs taught entirely in English, especially at the master''s and PhD levels. However, learning basic German will enhance your daily life experience.',
  faq4_question = 'Can I work while studying in Germany?',
  faq4_answer = 'Yes, international students can work up to 120 full days or 240 half days per year without requiring an additional work permit. This helps in funding your studies and gaining relevant work experience.',
  faq5_question = 'What are the visa requirements for studying in Germany?',
  faq5_answer = 'Non-EU/EEA students need a national visa (D-visa) for study purposes. Requirements include university acceptance letter, proof of financial resources (€10,332 per year), health insurance, and valid passport. Processing takes 4-6 weeks or longer.',
  faq6_question = 'Are there scholarships available for international students?',
  faq6_answer = 'Yes, various scholarships are available through DAAD (German Academic Exchange Service), individual universities (including Deutschland Stipendium), political foundations, and industry-sponsored programs. Application deadlines are typically several months before program start dates.',
  faq7_question = 'What accommodation options are available for students?',
  faq7_answer = 'Options include student dormitories (€250-350/month), shared apartments (WG) (€300-500/month), and private apartments (€500-800/month). Student dormitories offer the best value but have waiting lists, so apply early or consider private accommodation.',
  faq8_question = 'What healthcare provisions are there for international students?',
  faq8_answer = 'Health insurance is mandatory for all students in Germany. Students under 30 can join the public health insurance system for about €110/month. Those over 30 or from certain non-EU countries may need private insurance. Most medical costs are fully covered.'
WHERE slug = 'germany'; 