-- Update data for Ireland country
UPDATE countries
SET
  -- Basic Information
  capital = 'Dublin',
  population = '5.01 million (2021)',
  language = 'English, Irish (Gaelic)',
  currency = 'Euro (€)',
  academic_year = 'September to May',
  education_system = 'European Credit Transfer System (ECTS)',
  
  -- Education Statistics
  international_students = '32,000+',
  top_universities = '8 universities in global top 500',
  english_programs = '5,000+ programs taught in English',
  post_study_work = 'Up to 2 years (Third Level Graduate Programme)',
  
  -- Education System
  bachelor_info = 'Usually 3-4 years (180-240 ECTS). An honors bachelor''s degree (Level 8) typically takes 4 years, while an ordinary bachelor''s degree (Level 7) takes 3 years.',
  master_info = 'Usually 1-2 years (60-120 ECTS). Programs combine taught modules, research, and a dissertation.',
  phd_info = 'Usually 3-4 years. Research-based with a thesis. Some structured PhD programs include taught components.',
  teaching_style = 'Interactive and participatory approach, with emphasis on critical thinking, research skills, and practical application.',
  grading_system = 'First Class Honours (70%+), Second Class Honours Grade 1 (60-69%), Second Class Honours Grade 2 (50-59%), Third Class Honours (40-49%), Pass (40%), Fail (below 40%).',
  instruction_language = 'English is the primary language of instruction at all levels of education.',
  academic_calendar = 'Two semesters: September to December and January to May, with exams at the end of each semester.',
  universities_intro = 'Ireland has 7 public universities, 1 technological university, 5 institutes of technology, and several private colleges, known for high academic standards and research opportunities.',
  
  -- Admission & Visa Requirements
  educational_requirements = 'Completed secondary education equivalent to Irish Leaving Certificate. For master''s programs, a relevant bachelor''s degree is required.',
  transcript_requirements = 'Official transcripts from all previous institutions attended, translated to English if necessary.',
  entrance_exams = 'Generally not required for most programs, though some specialized courses may have specific entrance tests.',
  english_requirements = 'IELTS: typically 6.0-6.5 overall (minimum 5.5-6.0 in each component) for undergraduate, 6.5-7.0 for postgraduate.',
  language_exemptions = 'Students from countries where English is the primary language may be exempt from language tests.',
  visa_requirements = 'Non-EU/EEA students need a student visa. Must provide acceptance letter from an Irish institution and proof of tuition payment.',
  financial_requirements = 'Proof of sufficient funds to cover tuition and living expenses (approximately €10,000 per year plus tuition fees).',
  health_requirements = 'Private health insurance is mandatory for all non-EU students throughout their stay in Ireland.',
  additional_documents = 'Valid passport, passport-sized photographs, proof of accommodation, letter of acceptance from Irish institution.',
  visa_tip = 'Apply for your visa at least 8 weeks before your intended travel date, as processing times can vary.',
  
  -- Tuition & Living Costs
  bachelor_fee_public = '€10,500 - €24,000 per year',
  bachelor_fee_private = '€12,000 - €30,000 per year',
  bachelor_fee_medical = '€45,000 - €55,000 per year',
  master_fee_public = '€10,000 - €30,000 per year',
  master_fee_private = '€12,000 - €35,000 per year',
  master_fee_business = '€15,000 - €34,500 per program',
  accommodation_cost = '€500 - €1,200 per month',
  accommodation_note = 'University residence halls cost €500-800/month. Private rentals range from €700-1,200/month depending on location and type.',
  food_cost = '€250 - €350 per month',
  food_note = 'Cooking at home costs around €250/month. University canteens offer meals at discounted prices (€5-8 per meal).',
  transport_cost = '€50 - €120 per month',
  transport_note = 'Student travel cards offer discounted rates on public transport. Monthly passes cost around €80 in Dublin, less in other cities.',
  utilities_cost = '€100 - €150 per month',
  utilities_note = 'Includes electricity, heating, water, and internet. May be included in university accommodation fees.',
  other_cost = '€150 - €300 per month',
  other_note = 'Includes personal expenses, books, leisure activities, and phone bills.',
  total_monthly_cost = '€1,050 - €2,120 per month',
  budget_tip1 = 'Apply for the Student Leap Card to get discounts on public transportation, shops, and entertainment venues.',
  budget_tip2 = 'Consider university accommodation for your first year as it''s often more affordable and convenient.',
  budget_tip3 = 'Open an Irish bank account to avoid foreign transaction fees and make it easier to receive/make payments.',
  budget_tip4 = 'Look for part-time work opportunities (up to 20 hours per week during term time) to supplement your income.',
  government_scholarships = 'The Government of Ireland International Education Scholarships provides funding for high-caliber students to study in Ireland for one year.',
  university_scholarships = 'Most Irish universities offer merit-based scholarships for international students, covering partial or full tuition fees.',
  external_scholarships = 'Various organizations like Education in Ireland, Fulbright Commission, and country-specific funding bodies offer scholarships for study in Ireland.',
  
  -- Student Life
  campus_life = 'Irish universities offer vibrant campus environments with modern facilities, libraries, sports centers, and student unions organizing regular events and activities.',
  campus_life_extra = 'Students can join numerous clubs and societies catering to diverse interests including sports, arts, culture, politics, and academic pursuits.',
  work_opportunities = 'International students can work up to 20 hours per week during term time and full-time (40 hours) during scheduled holiday periods.',
  work_opportunities_extra = 'After graduation, the Third Level Graduate Programme allows non-EU/EEA students to remain in Ireland for 12-24 months to seek employment.',
  cultural_experience = 'Ireland is known for its rich cultural heritage, literary tradition, music, and festivals. Students can explore historic sites, stunning landscapes, and experience traditional Irish hospitality.',
  cultural_experience_extra = 'The country is safe and welcoming to international students, with English widely spoken, making it easier to adapt to life in Ireland.',
  student_life_image1 = '/images/placeholders/student-life-1.jpg',
  student_life_image2 = '/images/placeholders/student-life-2.jpg',
  student_life_image3 = '/images/placeholders/student-life-3.jpg',
  student_life_image4 = '/images/placeholders/student-life-4.jpg',
  
  -- Testimonials
  testimonial1_name = 'Aisha Khan',
  testimonial1_image = '/images/placeholders/testimonial-1.jpg',
  testimonial1_program = 'MSc in Data Science',
  testimonial1_university = 'Trinity College Dublin',
  testimonial1_quote = 'Studying in Ireland has been an incredible experience. The quality of education is excellent, and Dublin is such a vibrant city. The people are so friendly, and I''ve made friends from all over the world!',
  testimonial1_country = 'From India',
  testimonial2_name = 'Miguel Rodriguez',
  testimonial2_image = '/images/placeholders/testimonial-2.jpg',
  testimonial2_program = 'BA in Business Studies',
  testimonial2_university = 'University College Dublin',
  testimonial2_quote = 'The business program in UCD is world-class with excellent industry connections. I''ve had internship opportunities with major tech companies, and the international student support has been phenomenal.',
  testimonial2_country = 'From Mexico',
  testimonial3_name = 'Lin Wei',
  testimonial3_image = '/images/placeholders/testimonial-3.jpg',
  testimonial3_program = 'PhD in Biomedical Engineering',
  testimonial3_university = 'University College Cork',
  testimonial3_quote = 'The research facilities at UCC are state-of-the-art. My supervisors are leaders in their field and have provided exceptional guidance. Ireland''s scientific community is very collaborative and welcoming.',
  testimonial3_country = 'From China',
  
  -- FAQs
  faq1_question = 'What are the benefits of studying in Ireland?',
  faq1_answer = 'Ireland offers high-quality education with internationally recognized qualifications, English-taught programs, a safe and friendly environment, vibrant student life, and strong employment opportunities. Graduates from Irish institutions have a post-study work option of 1-2 years.',
  faq2_question = 'How much does it cost to study and live in Ireland?',
  faq2_answer = 'Tuition fees range from €10,500 to €55,000 per year depending on the program and institution. Living expenses typically amount to €1,050-€2,120 per month including accommodation, food, transport, and other personal expenses.',
  faq3_question = 'Do I need to speak Irish to study in Ireland?',
  faq3_answer = 'No, English is the primary language of instruction at all Irish universities. While Irish (Gaelic) is the first official language, it is not required for international students. All programs are taught in English.',
  faq4_question = 'Can I work while studying in Ireland?',
  faq4_answer = 'Yes, international students can work up to 20 hours per week during term time and up to 40 hours per week during scheduled holidays. This provides an opportunity to gain work experience and supplement your income.',
  faq5_question = 'What are the visa requirements for studying in Ireland?',
  faq5_answer = 'Non-EU/EEA students need a student visa. Requirements include an acceptance letter from an Irish institution, proof of tuition payment, evidence of sufficient funds (minimum €10,000 plus tuition), and private health insurance.',
  faq6_question = 'Are there scholarships available for international students?',
  faq6_answer = 'Yes, there are various scholarships available including the Government of Ireland International Education Scholarships, university-specific scholarships, and external funding from organizations like Education in Ireland and country-specific bodies.',
  faq7_question = 'What accommodation options are available for students?',
  faq7_answer = 'Options include university residence halls (€500-800/month), private student accommodations, shared apartments, and homestays. University accommodation is recommended for first-year students as it''s easier to arrange and often more affordable.',
  faq8_question = 'What is the post-study work option in Ireland?',
  faq8_answer = 'The Third Level Graduate Programme allows non-EU/EEA students to remain in Ireland for 12-24 months after graduation (depending on the level of study) to seek employment or apply for a work permit. This provides valuable time to gain work experience or start a career in Ireland.'
WHERE slug = 'ireland'; 