-- Update data for Japan country
UPDATE countries
SET
  -- Basic Information
  capital = 'Tokyo',
  population = '125.8 million (2021)',
  language = 'Japanese',
  currency = 'Japanese Yen (¥)',
  academic_year = 'April to March',
  education_system = 'Credit-based semester system',
  
  -- Education Statistics
  international_students = '310,000+',
  top_universities = '41 universities in global top 500',
  english_programs = '850+ programs taught in English',
  post_study_work = 'Up to 1 year (Designated Activities visa)',
  
  -- Education System
  bachelor_info = 'Usually 4 years (6 years for medicine, dentistry, and veterinary science). Programs combine general education with specialized studies in a major field. Focus on building strong fundamentals and specialized knowledge.',
  master_info = 'Usually 2 years. Research-oriented with coursework components, culminating in a thesis. Strong emphasis on original research contributions and academic depth.',
  phd_info = 'Usually 3 years after master''s degree. Research-focused, requiring publication in academic journals and a dissertation. Close mentorship from academic advisors and rigorous standards.',
  teaching_style = 'Traditional with evolving innovations. Lecture-based instruction in larger universities, with seminars and laboratory work for upper-level courses. Emphasis on thoroughness, attention to detail, and mastery of fundamentals.',
  grading_system = 'Typically a 100-point scale: 90-100 (Excellent/S), 80-89 (Good/A), 70-79 (Satisfactory/B), 60-69 (Pass/C), below 60 (Fail/F). Some universities use letter grades or a 4.0 GPA system.',
  instruction_language = 'Japanese is the primary language of instruction, though English-taught programs are increasingly available, especially at the graduate level and at internationally-oriented universities.',
  academic_calendar = 'Two semesters: Spring (April to August) and Fall (September to March), with examination periods at the end of each semester. Some universities offer fall admission for international students.',
  universities_intro = 'Japan has over 800 universities, including national, public, and private institutions. National universities like University of Tokyo and Kyoto University are highly prestigious research institutions, while many private universities also offer excellent education with distinct specializations.',
  
  -- Admission & Visa Requirements
  educational_requirements = 'For undergraduate: 12 years of education equivalent to Japanese high school. For graduate programs: bachelor''s degree in a relevant field. Educational background evaluation is typically required.',
  transcript_requirements = 'Official transcripts from all previous educational institutions, with grades and course descriptions. Japanese translations may be required for documents not in English or Japanese.',
  entrance_exams = 'The Examination for Japanese University Admission for International Students (EJU) is required for many undergraduate programs. JLPT (Japanese Language Proficiency Test) may be required for Japanese-taught programs. Some English programs accept SAT, ACT, IB, or A-levels.',
  english_requirements = 'For English-taught programs: TOEFL iBT (typically 80-100), IELTS (typically 6.0-7.0), or equivalent scores depending on the university and program level.',
  language_exemptions = 'Students from countries where English is the primary language of instruction may be exempt from English proficiency tests for English-taught programs.',
  visa_requirements = 'Student visa ("College Student" status) required for programs lasting more than 3 months. Requires Certificate of Eligibility issued by Japanese Immigration Bureau, which the university usually helps obtain.',
  financial_requirements = 'Proof of sufficient funds to cover tuition and living expenses (approximately 1,500,000-2,000,000 JPY per year plus tuition). Documentation typically includes bank statements, scholarship certificates, or sponsor guarantees.',
  health_requirements = 'National Health Insurance is mandatory for international students staying more than 3 months. Students typically undergo a health check upon enrollment.',
  additional_documents = 'Valid passport, passport-sized photographs, Certificate of Eligibility, acceptance letter from a Japanese institution, proof of financial resources, and personal statement or research plan for graduate studies.',
  visa_tip = 'Begin the visa application process at least 3-4 months before your intended departure, as the Certificate of Eligibility processing can take 1-3 months. Once you receive the COE, the actual visa processing is usually quick (about 5 business days).',
  
  -- Tuition & Living Costs
  bachelor_fee_public = 'JPY 535,800 per year (admission fee: JPY 282,000)',
  bachelor_fee_private = 'JPY 800,000 - 1,500,000 per year',
  bachelor_fee_medical = 'JPY 3,000,000 - 5,000,000 per year',
  master_fee_public = 'JPY 535,800 per year (admission fee: JPY 282,000)',
  master_fee_private = 'JPY 900,000 - 1,600,000 per year',
  master_fee_business = 'JPY 1,800,000 - 3,500,000 per program',
  accommodation_cost = 'JPY 30,000 - 100,000 per month',
  accommodation_note = 'University dormitories are the most affordable (JPY 30,000-50,000/month), but have limited availability. Private apartments cost JPY 50,000-100,000/month depending on location, with Tokyo being significantly more expensive than other cities.',
  food_cost = 'JPY 30,000 - 60,000 per month',
  food_note = 'University cafeterias offer affordable meals (JPY 400-700 per meal). Cooking at home and utilizing supermarket evening discounts can significantly reduce food expenses.',
  transport_cost = 'JPY 5,000 - 20,000 per month',
  transport_note = 'Student commuter passes offer discounts on trains and buses. Living close to campus can reduce transportation costs. Bicycles are a cost-effective option in many cities.',
  utilities_cost = 'JPY 10,000 - 25,000 per month',
  utilities_note = 'Includes electricity, gas, water, and internet. Costs vary seasonally, with higher expenses during summer (air conditioning) and winter (heating).',
  other_cost = 'JPY 15,000 - 30,000 per month',
  other_note = 'Includes phone plans, books, leisure activities, and personal expenses. Health insurance costs approximately JPY 20,000 per year for the National Health Insurance.',
  total_monthly_cost = 'JPY 90,000 - 235,000 per month',
  budget_tip1 = 'Apply for JASSO scholarships and university-specific financial aid, which are available specifically for international students with solid academic records.',
  budget_tip2 = 'Use student discounts (with your student ID) for transportation, museums, cinemas, and other services throughout Japan.',
  budget_tip3 = 'Shop at 100-yen shops for everyday necessities and take advantage of seasonal sales and discount stores for clothing and other items.',
  budget_tip4 = 'Consider part-time work (up to 28 hours per week during term, 40 hours during holidays) to supplement your income. Teaching English is a popular and well-paid option.',
  government_scholarships = 'MEXT (Japanese Government) Scholarships provide generous funding covering tuition, living expenses, and airfare for exceptional international students.',
  university_scholarships = 'Many Japanese universities offer tuition reduction or exemption (30-100%) and monthly stipends for outstanding international students.',
  external_scholarships = 'JASSO (Japan Student Services Organization) scholarships, corporate foundations, and home country organizations provide various funding opportunities for study in Japan.',
  
  -- Student Life
  campus_life = 'Japanese campuses vary from traditional to ultra-modern, with comprehensive facilities including libraries, research centers, sports facilities, and student centers.',
  campus_life_extra = 'Student clubs (circles) are essential to campus life, covering everything from academics and arts to sports and hobbies. Joining circles is the best way to make Japanese friends and practice language skills.',
  work_opportunities = 'International students can work up to 28 hours per week during term time and 40 hours during official vacation periods with a "Permission to Engage in Activity Other than that Permitted by the Status of Residence Previously Granted" from immigration.',
  work_opportunities_extra = 'After graduation, international students can apply for a Designated Activities visa to search for employment for up to 1 year. Japan''s aging population has created labor shortages, offering good job prospects in many fields, especially for those with Japanese language skills.',
  cultural_experience = 'Japan offers a unique blend of ancient traditions and cutting-edge modernity. Students can experience traditional arts, festivals, cuisine, and historical sites while also enjoying contemporary Japanese pop culture, technology, and urban life.',
  cultural_experience_extra = 'Four distinct seasons bring different cultural experiences, from cherry blossom viewing in spring to autumn leaves, winter illuminations, and summer festivals. Japan''s excellent transportation system makes exploring the country convenient and safe.',
  student_life_image1 = '/images/placeholders/student-life-1.jpg',
  student_life_image2 = '/images/placeholders/student-life-2.jpg',
  student_life_image3 = '/images/placeholders/student-life-3.jpg',
  student_life_image4 = '/images/placeholders/student-life-4.jpg',
  
  -- Testimonials
  testimonial1_name = 'Michael Johnson',
  testimonial1_image = '/images/placeholders/testimonial-1.jpg',
  testimonial1_program = 'Master of Engineering',
  testimonial1_university = 'Tokyo Institute of Technology',
  testimonial1_quote = 'Studying engineering in Japan has been an incredible opportunity to experience cutting-edge technology and precision manufacturing firsthand. Laboratory work is taken very seriously, and I''ve had access to equipment I couldn''t find elsewhere. The emphasis on quality and attention to detail has transformed my approach to engineering problems.',
  testimonial1_country = 'From United States',
  testimonial2_name = 'Maria Garcia',
  testimonial2_image = '/images/placeholders/testimonial-2.jpg',
  testimonial2_program = 'Bachelor of Arts in Japanese Studies',
  testimonial2_university = 'Waseda University',
  testimonial2_quote = 'Immersing myself in Japanese culture while studying has been a dream come true. The language support at Waseda is excellent, and I''ve made friends from all over the world. Tokyo is incredibly safe and convenient, though it took time to adapt to the pace of life. Joining a traditional tea ceremony club gave me insights into Japanese culture I couldn''t get from textbooks.',
  testimonial2_country = 'From Spain',
  testimonial3_name = 'Liu Wei',
  testimonial3_image = '/images/placeholders/testimonial-3.jpg',
  testimonial3_program = 'PhD in Robotics',
  testimonial3_university = 'Osaka University',
  testimonial3_quote = 'Japan''s reputation for robotics excellence is well-deserved. My research laboratory collaborates with major technology companies, giving us access to industry insights and future job opportunities. The research funding is generous, and the mentorship from professors is outstanding. Osaka offers a more relaxed atmosphere than Tokyo while still providing world-class research facilities.',
  testimonial3_country = 'From China',
  
  -- FAQs
  faq1_question = 'What are the benefits of studying in Japan?',
  faq1_answer = 'Benefits include high-quality education and research opportunities, cutting-edge technology, safe and clean environment, unique cultural experiences, increasing number of English-taught programs, various scholarship options, part-time work opportunities, and potential career paths in Japan''s global companies.',
  faq2_question = 'How much does it cost to study and live in Japan?',
  faq2_answer = 'Tuition at national universities is approximately 535,800 yen per year plus a one-time admission fee. Private universities range from 800,000-1,500,000 yen annually (higher for medical fields). Monthly living expenses range from 90,000-235,000 yen depending on location, with Tokyo being the most expensive.',
  faq3_question = 'Do I need to speak Japanese to study in Japan?',
  faq3_answer = 'Not necessarily. Over 850 programs are taught entirely in English, especially at the graduate level. However, learning basic Japanese will significantly enhance your daily life and cultural experience. Many universities offer Japanese language courses alongside regular academic programs.',
  faq4_question = 'Can I work while studying in Japan?',
  faq4_answer = 'Yes, international students can work up to 28 hours per week during term time and 40 hours during official vacation periods with proper permission from immigration. Common part-time jobs include English teaching, restaurant work, retail, and university research assistantships.',
  faq5_question = 'What are the visa requirements for studying in Japan?',
  faq5_answer = 'You need a student visa ("College Student" status) for programs lasting more than 3 months. The process requires a Certificate of Eligibility from Japanese immigration, usually processed through your host institution, followed by a visa application at the Japanese embassy/consulate in your home country.',
  faq6_question = 'Are there scholarships available for international students?',
  faq6_answer = 'Yes, numerous scholarships are available including the prestigious MEXT (Japanese Government) Scholarship, JASSO scholarships, university-specific scholarships (often providing tuition reduction), and various private foundation awards. Application requirements and deadlines vary widely.',
  faq7_question = 'What is the academic calendar in Japan?',
  faq7_answer = 'The academic year typically begins in April and ends in March, with two semesters: April-August and September-March. Some universities offer fall enrollment (September/October) specifically for international students to align with global academic calendars.',
  faq8_question = 'What are the career prospects after studying in Japan?',
  faq8_answer = 'Graduates can obtain a Designated Activities visa to job-hunt for up to one year. Japan''s aging population and internationalization efforts have created demand for foreign talent, especially in IT, engineering, international business, and tourism. Japanese language proficiency significantly improves employment prospects.'
WHERE slug = 'japan'; 