-- Update data for Netherlands country
UPDATE countries
SET
  -- Basic Information
  capital = 'Amsterdam',
  population = '17.5 million (2021)',
  language = 'Dutch (Nederlands)',
  currency = 'Euro (€)',
  academic_year = 'September to June',
  education_system = 'European Credit Transfer System (ECTS)',
  
  -- Education Statistics
  international_students = '115,000+',
  top_universities = '13 universities in global top 200',
  english_programs = '2,100+ programs taught in English',
  post_study_work = 'Up to 12 months (Orientation Year permit)',
  
  -- Education System
  bachelor_info = 'Usually 3 years (180 ECTS) at research universities, 4 years (240 ECTS) at universities of applied sciences. Research university programs are more theoretical, while applied sciences universities focus on practical skills and professional training.',
  master_info = 'Usually 1-2 years (60-120 ECTS). Research-oriented master''s programs emphasize independent research, while professional master''s focus on applying knowledge in specific fields. Highly specialized with close industry connections.',
  phd_info = 'Usually 4 years. Research-focused with a dissertation defense. Unlike many countries, PhD candidates in the Netherlands are often university employees receiving salaries rather than paying tuition, though external/self-funded positions also exist.',
  teaching_style = 'Progressive and student-centered approach emphasizing critical thinking, problem-solving, and independent learning. Features interactive seminars, group projects, presentations, and close faculty-student interaction.',
  grading_system = 'Based on a 10-point scale: 10 (outstanding), 9 (very good), 8 (good), 7 (more than satisfactory), 6 (satisfactory/pass), 5-1 (fail). The minimum passing grade is 6, and grades 9-10 are rarely awarded.',
  instruction_language = 'Over 2,100 programs are taught entirely in English, especially at the master''s level. Dutch is used in some undergraduate programs, though English-taught options are abundant across all disciplines.',
  academic_calendar = 'Two semesters: Fall (September to January) and Spring (February to June), with examination periods at the end of each semester. Some universities use a trimester or quarter system.',
  universities_intro = 'The Netherlands has 14 research universities and 36 universities of applied sciences. Dutch universities are known for their high-quality education, innovative research, and strong international orientation. Many rank among the world''s best institutions.',
  
  -- Admission & Visa Requirements
  educational_requirements = 'For Bachelor''s: Secondary school diploma equivalent to Dutch VWO or HAVO. For Master''s: Bachelor''s degree in a relevant field. Credential evaluation is often required for non-EU qualifications.',
  transcript_requirements = 'Official transcripts from all previous educational institutions, with grades and course descriptions. Dutch universities look for a strong academic record, especially in subjects relevant to your chosen program.',
  entrance_exams = 'Generally not required for most programs, though some competitive or specialized fields like medicine may have entrance exams or selection procedures. Portfolio assessment may be required for creative disciplines.',
  english_requirements = 'IELTS: typically 6.0-7.0 overall for undergraduate, 6.5-7.5 for postgraduate. TOEFL iBT: 80-100. Cambridge English qualifications and other tests may also be accepted, depending on the institution.',
  language_exemptions = 'Students from the USA, UK, Ireland, Australia, New Zealand, Canada, and other countries where English is the primary language of instruction may be exempt from language tests.',
  visa_requirements = 'EU/EEA students don''t need a visa. Non-EU/EEA students need an entry visa (MVV) and a residence permit. The university handles most of the application process through the fast-track procedure.',
  financial_requirements = 'Proof of sufficient funds to cover living expenses (approximately €10,800 per year) plus tuition fees. This can be shown through bank statements, scholarship letters, or sponsor declarations.',
  health_requirements = 'Health insurance is mandatory for all international students. EU students can use their European Health Insurance Card (EHIC), while non-EU students must purchase Dutch health insurance.',
  additional_documents = 'Valid passport, acceptance letter from a Dutch institution, proof of accommodation, passport-sized photographs, and tuberculosis test (for certain nationalities).',
  visa_tip = 'Start your visa application process as soon as you receive your acceptance letter, as processing can take 4-8 weeks. Your host institution will guide you through most of the process, but be prepared to submit documents quickly when requested.',
  
  -- Tuition & Living Costs
  bachelor_fee_public = 'EU/EEA: €2,200 per year, Non-EU/EEA: €6,000 - 15,000 per year',
  bachelor_fee_private = 'EUR 8,000 - 20,000 per year',
  bachelor_fee_medical = 'EUR 20,000 - 32,000 per year',
  master_fee_public = 'EU/EEA: €2,200 per year, Non-EU/EEA: €8,000 - 20,000 per year',
  master_fee_private = 'EUR 10,000 - 25,000 per year',
  master_fee_business = 'EUR 15,000 - 40,000 per program',
  accommodation_cost = 'EUR 350 - 900 per month',
  accommodation_note = 'Student housing costs €350-650/month in most cities, while private rentals range from €450-900/month depending on location. Amsterdam and Utrecht have the highest housing costs, while smaller cities are more affordable.',
  food_cost = 'EUR 200 - 350 per month',
  food_note = 'Grocery shopping amounts to approximately €200-250/month for basic necessities. University canteens offer affordable meals (€5-10). Eating out regularly will increase costs substantially.',
  transport_cost = 'EUR 50 - 100 per month',
  transport_note = 'Public transportation costs can be reduced with the student OV-chipkaart, which provides discounts. Many students use bicycles as the primary mode of transportation, which is essentially free after the initial purchase.',
  utilities_cost = 'EUR 100 - 200 per month',
  utilities_note = 'Includes electricity, heating, water, and internet. Often partially included in student housing fees or rental agreements.',
  other_cost = 'EUR 100 - 200 per month',
  other_note = 'Includes phone plans, books, leisure activities, and personal expenses. Health insurance costs approximately €100-120 per month.',
  total_monthly_cost = 'EUR 800 - 1,750 per month',
  budget_tip1 = 'Get a bicycle for transportation - it''s the most economical and typical Dutch way to get around, saving significantly on public transport costs.',
  budget_tip2 = 'Apply for student housing through your university or student housing organizations as early as possible, as affordable options fill up quickly.',
  budget_tip3 = 'Open a Dutch bank account to avoid foreign transaction fees, and look into student discounts available with your university card.',
  budget_tip4 = 'Consider part-time work (up to 16 hours per week for non-EU students, unlimited for EU students) to supplement your income. Many service industry positions only require English.',
  government_scholarships = 'The Dutch government offers Orange Knowledge Programme, Holland Scholarship, and Erasmus+ funding opportunities for international students.',
  university_scholarships = 'Many Dutch universities have their own scholarship programs for international students based on academic excellence, country of origin, or specific fields of study.',
  external_scholarships = 'Various foundations, private organizations, and country-specific programs offer scholarships for study in the Netherlands. The Nuffic Scholarship Finder is a good resource.',
  
  -- Student Life
  campus_life = 'Dutch universities typically have facilities spread across their host city rather than a single enclosed campus. Modern academic buildings, libraries, research facilities, and student centers form the university infrastructure.',
  campus_life_extra = 'Active student associations organize social events, sports activities, cultural outings, and career networking opportunities. Introduction weeks help new students integrate into university life and make friends.',
  work_opportunities = 'EU/EEA students can work without restrictions. Non-EU/EEA students can work up to 16 hours per week during term time OR full-time during summer months (June-August), requiring a work permit arranged by the employer.',
  work_opportunities_extra = 'After graduation, the Orientation Year permit allows international graduates to stay for up to 12 months to find employment or start a business. The Netherlands has a thriving job market for English speakers, especially in technology, engineering, business, and creative industries.',
  cultural_experience = 'The Netherlands offers a progressive, open-minded society with rich cultural heritage, including museums, historic cities, and traditions like King''s Day. Dutch directness, efficiency, and work-life balance are distinct cultural characteristics.',
  cultural_experience_extra = 'The country''s compact size and excellent transportation system make it easy to explore both urban centers and scenic countryside. The central location in Europe makes it an ideal base for traveling to neighboring countries.',
  student_life_image1 = '/images/placeholders/student-life-1.jpg',
  student_life_image2 = '/images/placeholders/student-life-2.jpg',
  student_life_image3 = '/images/placeholders/student-life-3.jpg',
  student_life_image4 = '/images/placeholders/student-life-4.jpg',
  
  -- Testimonials
  testimonial1_name = 'Sofia Petrescu',
  testimonial1_image = '/images/placeholders/testimonial-1.jpg',
  testimonial1_program = 'MSc in Artificial Intelligence',
  testimonial1_university = 'University of Amsterdam',
  testimonial1_quote = 'The Dutch approach to education encourages critical thinking and innovation in ways I hadn''t experienced before. My program offers perfect balance between theoretical foundations and practical applications. And living in Amsterdam has been amazing - it''s international, welcoming, and there''s always something happening!',
  testimonial1_country = 'From Romania',
  testimonial2_name = 'Raj Patel',
  testimonial2_image = '/images/placeholders/testimonial-2.jpg',
  testimonial2_program = 'Bachelor of International Business',
  testimonial2_university = 'Rotterdam University of Applied Sciences',
  testimonial2_quote = 'Studying in Rotterdam has given me direct exposure to one of Europe''s most important business hubs. The practice-based learning approach includes real company projects and internships that build valuable skills and connections. The international student community is diverse and supportive.',
  testimonial2_country = 'From India',
  testimonial3_name = 'Emma Chen',
  testimonial3_image = '/images/placeholders/testimonial-3.jpg',
  testimonial3_program = 'PhD in Water Management',
  testimonial3_university = 'Delft University of Technology',
  testimonial3_quote = 'The Netherlands is world-renowned in water management, making TU Delft the perfect place for my research. As a PhD candidate, I''m treated as a professional researcher with a salary rather than a student paying tuition. The collaborative research environment and industry partnerships have opened many doors.',
  testimonial3_country = 'From China',
  
  -- FAQs
  faq1_question = 'What are the benefits of studying in the Netherlands?',
  faq1_answer = 'Key benefits include high-quality education with many English-taught programs, affordable tuition compared to the UK or US, strong international orientation, innovative teaching methods, excellent research facilities, post-study work opportunities, high quality of life, and central location in Europe ideal for travel.',
  faq2_question = 'How much does it cost to study and live in the Netherlands?',
  faq2_answer = 'EU/EEA students pay approximately €2,200 per year in tuition, while non-EU/EEA students pay €6,000-32,000 depending on the program. Living expenses range from €800-1,750 per month depending on the city, with Amsterdam being the most expensive and smaller cities more affordable.',
  faq3_question = 'Do I need to speak Dutch to study in the Netherlands?',
  faq3_answer = 'No, there are over 2,100 English-taught programs, and most Dutch people speak excellent English. While not necessary for your studies, learning some basic Dutch can enrich your daily life experience and may be beneficial if you plan to work in the Netherlands after graduating.',
  faq4_question = 'Can I work while studying in the Netherlands?',
  faq4_answer = 'EU/EEA students can work without restrictions. Non-EU/EEA students can work either part-time (max 16 hours per week) during the academic year OR full-time during summer months (June-August). Employers must arrange a work permit, but many student jobs are available, especially in larger cities.',
  faq5_question = 'What are the visa requirements for studying in the Netherlands?',
  faq5_answer = 'EU/EEA students only need a valid ID/passport and must register with the local municipality. Non-EU/EEA students need an entry visa (MVV) and residence permit, requiring acceptance from a recognized institution, sufficient financial resources, health insurance, and a clear criminal record.',
  faq6_question = 'Are there scholarships available for international students?',
  faq6_answer = 'Yes, scholarships are available through the Dutch government (Orange Knowledge Programme, Holland Scholarship), individual universities, and external organizations. Most are merit-based and competitive, with application deadlines usually several months before programs begin.',
  faq7_question = 'What is the difference between research universities and universities of applied sciences?',
  faq7_answer = 'Research universities (WO) offer more theoretical, research-oriented education preparing students for independent research or professional roles requiring scientific knowledge. Universities of applied sciences (HBO) provide practical, profession-oriented education preparing students directly for specific careers or industries.',
  faq8_question = 'What are the post-graduation opportunities in the Netherlands?',
  faq8_answer = 'Graduates can apply for the Orientation Year permit, allowing them to stay for up to 12 months to find a job or start a business without needing employer sponsorship. The Netherlands has a favorable highly skilled migrant program and many international companies seeking English-speaking graduates, particularly in technology, engineering, and business sectors.'
WHERE slug = 'netherlands'; 