-- Update data for Poland country
UPDATE countries
SET
  -- Basic Information
  capital = 'Warsaw',
  population = '38 million (2021)',
  language = 'Polish',
  currency = 'Polish Złoty (PLN)',
  academic_year = 'October to June',
  education_system = 'European Credit Transfer System (ECTS)',
  
  -- Education Statistics
  international_students = '85,000+',
  top_universities = '10 universities in global top 1000',
  english_programs = '800+ programs taught in English',
  post_study_work = 'Up to 9 months to seek employment',
  
  -- Education System
  bachelor_info = 'Usually 3 years (180 ECTS). Called "Licencjat" for arts/humanities or "Inżynier" for technical/engineering fields. Provides solid academic foundation with both theoretical and practical components.',
  master_info = 'Usually 2 years (120 ECTS). Called "Magister" or "Magister Inżynier" for technical fields. Focuses on advanced knowledge and specialized skills in the chosen field.',
  phd_info = 'Usually 3-4 years. Research-focused with some taught components. Requires a master''s degree for admission and defense of original dissertation.',
  teaching_style = 'Traditional with increasing focus on interactive methods. Strong theoretical foundation combined with practical applications. Emphasis on specialized knowledge in the chosen field.',
  grading_system = '5.0 (Very Good), 4.5 (Good Plus), 4.0 (Good), 3.5 (Satisfactory Plus), 3.0 (Satisfactory), 2.0 (Unsatisfactory/Fail). The higher the number, the better the grade.',
  instruction_language = 'Polish is the traditional language of instruction, but there are increasing numbers of programs taught entirely in English, especially at master''s and PhD levels.',
  academic_calendar = 'Two semesters: Winter semester (October to February) and Summer semester (February to June), with examination periods at the end of each semester.',
  universities_intro = 'Poland has over 400 higher education institutions, including traditional universities, technical universities, medical universities, and specialized academies. Both public and private institutions offer high-quality education.',
  
  -- Admission & Visa Requirements
  educational_requirements = 'For Bachelor''s: High school diploma equivalent to Polish Matura. For Master''s: Bachelor''s degree in a relevant field. Documents must be apostilled or legalized.',
  transcript_requirements = 'Official transcripts from previous educational institutions with grades, translated into Polish or English by a sworn translator.',
  entrance_exams = 'Generally not required for most programs, though some specialized fields like medicine, architecture, or arts may require entrance exams or portfolio submissions.',
  english_requirements = 'For English-taught programs: IELTS (6.0-6.5), TOEFL (75-90 iBT), or equivalent certificates depending on the program and university.',
  language_exemptions = 'Students from countries where English is the official language or those who completed previous education in English may be exempt from language tests.',
  visa_requirements = 'Non-EU/EEA students need a national visa (D-visa) for study purposes, followed by a temporary residence permit once in Poland.',
  financial_requirements = 'Proof of sufficient funds for living expenses (approximately PLN 800/month or €2,500 per year) and tuition fees.',
  health_requirements = 'Health insurance is mandatory. EU students can use European Health Insurance Card (EHIC), while non-EU students need to purchase insurance from the National Health Fund (NFZ) or a private provider.',
  additional_documents = 'Valid passport, acceptance letter from a Polish university, proof of accommodation, passport-sized photographs, medical certificate (if required by the university).',
  visa_tip = 'Apply for your visa at least 2-3 months before your planned departure. The visa process can take 2-4 weeks, but it''s better to allow extra time, especially during peak application periods.',
  
  -- Tuition & Living Costs
  bachelor_fee_public = 'EUR 2,000 - 3,500 per year',
  bachelor_fee_private = 'EUR 2,500 - 6,000 per year',
  bachelor_fee_medical = 'EUR 10,000 - 15,000 per year',
  master_fee_public = 'EUR 2,000 - 4,000 per year',
  master_fee_private = 'EUR 3,000 - 6,000 per year',
  master_fee_business = 'EUR 5,000 - 8,000 per program',
  accommodation_cost = 'PLN 400 - 1,200 per month',
  accommodation_note = 'University dormitories are the most affordable (PLN 400-800/month), while private rentals range from PLN 800-2,000/month depending on location and type.',
  food_cost = 'PLN 500 - 800 per month',
  food_note = 'University canteens offer affordable meals (PLN 15-25). Grocery shopping costs around PLN 400-600/month for basic necessities.',
  transport_cost = 'PLN 50 - 130 per month',
  transport_note = 'Student discounts of 50% are available on public transportation. Monthly passes cost around PLN 50-130 depending on the city.',
  utilities_cost = 'PLN 200 - 400 per month',
  utilities_note = 'Includes electricity, heating, water, and internet. Often partially included in dormitory fees.',
  other_cost = 'PLN 200 - 400 per month',
  other_note = 'Includes books, leisure activities, phone plans, and personal expenses.',
  total_monthly_cost = 'PLN 1,350 - 3,130 per month',
  budget_tip1 = 'Get an International Student Identity Card (ISIC) for additional discounts on transportation, museums, cinemas, and other services.',
  budget_tip2 = 'Consider sharing an apartment with other students to reduce accommodation costs, especially in larger cities like Warsaw or Krakow.',
  budget_tip3 = 'Use student canteens for affordable meals, and shop at local markets for fresh and inexpensive groceries.',
  budget_tip4 = 'Open a Polish bank account to avoid foreign transaction fees and easily pay bills and rent.',
  government_scholarships = 'The Polish National Agency for Academic Exchange (NAWA) offers various scholarship programs for international students at all levels of education.',
  university_scholarships = 'Many Polish universities offer merit-based scholarships covering partial or full tuition fees for outstanding international students.',
  external_scholarships = 'Visegrad Fund, Erasmus+, and bilateral agreements between Poland and other countries provide additional funding opportunities for international students.',
  
  -- Student Life
  campus_life = 'Polish universities typically have campuses integrated into city centers or dedicated areas with academic buildings, libraries, laboratories, and student facilities.',
  campus_life_extra = 'Student organizations, clubs, and associations offer various activities, events, and networking opportunities. International student offices provide support with adaptation and practical matters.',
  work_opportunities = 'International students can work without additional permits during their studies. EU/EEA students have no restrictions, while non-EU students can work up to 20 hours per week during the academic year and full-time during holidays.',
  work_opportunities_extra = 'After graduation, international students can apply for a temporary residence permit to seek employment for up to 9 months. English-speaking job opportunities are available, especially in larger cities and multinational corporations.',
  cultural_experience = 'Poland offers rich historical and cultural experiences with its medieval cities, castles, museums, and vibrant cultural events. Each region has its unique traditions, cuisine, and festivals.',
  cultural_experience_extra = 'The country''s central location in Europe makes it ideal for traveling to neighboring countries. Poland has diverse landscapes, from Baltic Sea beaches to Tatra mountains, offering various recreational activities.',
  student_life_image1 = '/images/placeholders/student-life-1.jpg',
  student_life_image2 = '/images/placeholders/student-life-2.jpg',
  student_life_image3 = '/images/placeholders/student-life-3.jpg',
  student_life_image4 = '/images/placeholders/student-life-4.jpg',
  
  -- Testimonials
  testimonial1_name = 'Elena Sokolov',
  testimonial1_image = '/images/placeholders/testimonial-1.jpg',
  testimonial1_program = 'MSc in Computer Science',
  testimonial1_university = 'Warsaw University of Technology',
  testimonial1_quote = 'Studying in Poland has been an incredible experience. The education quality is excellent, and the cost of living is much more affordable than in Western Europe. Warsaw has a vibrant tech scene with many opportunities for internships and networking.',
  testimonial1_country = 'From Ukraine',
  testimonial2_name = 'Mohammed Ali',
  testimonial2_image = '/images/placeholders/testimonial-2.jpg',
  testimonial2_program = 'Bachelor of Medicine',
  testimonial2_university = 'Medical University of Warsaw',
  testimonial2_quote = 'The medical program in Poland is rigorous and well-respected internationally. I appreciate the hands-on clinical experience from early years, and the multicultural environment has enriched my education. The affordability compared to other countries was a major factor in my decision.',
  testimonial2_country = 'From Egypt',
  testimonial3_name = 'Tanvi Sharma',
  testimonial3_image = '/images/placeholders/testimonial-3.jpg',
  testimonial3_program = 'MBA',
  testimonial3_university = 'Kozminski University',
  testimonial3_quote = 'My MBA experience in Poland has exceeded expectations. The program has a good balance of theoretical knowledge and practical case studies, with many courses taught by industry professionals. I''ve found Warsaw to be a welcoming city with a growing international business community.',
  testimonial3_country = 'From India',
  
  -- FAQs
  faq1_question = 'What are the benefits of studying in Poland?',
  faq1_answer = 'Key benefits include affordable tuition fees and living costs, high-quality education with globally recognized qualifications, growing number of English-taught programs, central European location ideal for travel, rich cultural heritage, and post-study work opportunities.',
  faq2_question = 'How much does it cost to study and live in Poland?',
  faq2_answer = 'Tuition fees range from €2,000-6,000 per year for most programs (higher for medical fields). Living expenses average €350-700 per month depending on the city, making Poland one of the most affordable study destinations in the European Union.',
  faq3_question = 'Do I need to speak Polish to study in Poland?',
  faq3_answer = 'Not necessarily. There are over 800 programs taught entirely in English. However, learning basic Polish will enhance your daily life experience and help with integration. Many universities offer free or low-cost Polish language courses for international students.',
  faq4_question = 'Can I work while studying in Poland?',
  faq4_answer = 'Yes, EU/EEA students can work without restrictions. Non-EU students can work up to 20 hours per week during the academic year and full-time during holidays without additional work permits, as long as they have a valid residence permit for studies.',
  faq5_question = 'What are the visa requirements for studying in Poland?',
  faq5_answer = 'EU/EEA citizens don''t need a visa but should register their stay if it exceeds 3 months. Non-EU/EEA students need a national visa (D-visa) for study purposes, which requires university acceptance letter, proof of financial resources, health insurance, and valid passport.',
  faq6_question = 'Are there scholarships available for international students?',
  faq6_answer = 'Yes, scholarships are available through the Polish National Agency for Academic Exchange (NAWA), individual universities, the Visegrad Fund (for V4 country citizens), and bilateral agreements between Poland and other countries. Application requirements and deadlines vary.',
  faq7_question = 'What accommodation options are available for students?',
  faq7_answer = 'Options include university dormitories (PLN 400-800/month), private student residences (PLN 800-1,400/month), and shared apartments (PLN 800-2,000/month). University dormitories are most affordable but have limited places, so early application is recommended.',
  faq8_question = 'What healthcare provisions are there for international students?',
  faq8_answer = 'EU/EEA students can use their European Health Insurance Card (EHIC). Non-EU students must have health insurance, either through the National Health Fund (NFZ) for about PLN 60/month or a private provider. Most universities have medical facilities on campus or nearby.'
WHERE slug = 'poland'; 