-- Update data for Singapore country
UPDATE countries
SET
  -- Basic Information
  capital = 'Singapore',
  population = '5.7 million (2021)',
  language = 'English (official), Mandarin, Malay, Tamil',
  currency = 'Singapore Dollar (SGD)',
  academic_year = 'August to May',
  education_system = 'Modular credit system',
  
  -- Education Statistics
  international_students = '86,000+',
  top_universities = '3 universities in global top 50',
  english_programs = '6,000+ programs taught in English',
  post_study_work = 'Up to 1 year (POWD)',
  
  -- Education System
  bachelor_info = 'Usually 3-4 years. Programs are rigorous and globally recognized, offering specializations across multiple disciplines. Strong emphasis on critical thinking, problem-solving, and practical skills development.',
  master_info = 'Usually 1-2 years. Programs combine coursework with research components (thesis or capstone projects). Strong industry connections provide practical exposure and networking opportunities.',
  phd_info = 'Usually 3-5 years. Research-focused with required coursework in early stages. Singapore universities offer generous funding for PhD candidates, including research grants and conference support.',
  teaching_style = 'Modern and interactive approach with strong emphasis on critical thinking, innovation, and practical application. Features a mix of lectures, tutorials, group projects, case studies, and extensive use of technology.',
  grading_system = 'Most universities use a 5.0 GPA scale or letter grades: A+ to F. Strong emphasis on continuous assessment alongside final examinations, with competitive grading curves in many programs.',
  instruction_language = 'English is the primary language of instruction across all institutions and programs, reflecting Singapore''s status as an international education hub.',
  academic_calendar = 'Two semesters: Semester 1 (August to December) and Semester 2 (January to May), with optional special terms during summer (May to July).',
  universities_intro = 'Singapore hosts world-class universities including National University of Singapore (NUS), Nanyang Technological University (NTU), and Singapore Management University (SMU), alongside international campuses of renowned institutions like INSEAD and Yale-NUS College.',
  
  -- Admission & Visa Requirements
  educational_requirements = 'For undergraduate: Completed secondary education with strong academic performance (A-levels, IB, or equivalent). For graduate programs: Bachelor''s degree in a relevant field with competitive GPA (typically 3.0/4.0 or higher).',
  transcript_requirements = 'Official transcripts from all previous educational institutions, with certified English translations if originals are not in English. Credential evaluation may be required for certain qualifications.',
  entrance_exams = 'SAT/ACT may be required for some undergraduate programs. Graduate programs often require GRE/GMAT (especially for business and STEM fields). Some specialized programs have discipline-specific entrance tests.',
  english_requirements = 'IELTS: typically 6.5 overall (minimum 6.0 in each component) for undergraduate, 6.5-7.0 for postgraduate. TOEFL iBT: 85-100, depending on the program. Cambridge English and PTE Academic also accepted by most institutions.',
  language_exemptions = 'Students from countries where English is the primary medium of instruction (e.g., US, UK, Australia, New Zealand) or who have completed previous education in English may be exempt from language tests.',
  visa_requirements = 'Student''s Pass required for full-time study, issued by the Immigration & Checkpoints Authority (ICA) through the Student''s Pass Online Application & Registration (SOLAR) system. Universities typically guide students through this process.',
  financial_requirements = 'Proof of sufficient funds to cover tuition and living expenses, though explicit financial statements are not always required as part of the visa application. Some universities may request financial guarantees for admission.',
  health_requirements = 'Medical examination including chest X-ray and HIV test required for Student''s Pass. Private health insurance is strongly recommended, and many universities provide basic coverage.',
  additional_documents = 'Valid passport, passport-sized photographs, acceptance letter from a Singapore institution, housing arrangements (if available), and completed eForm 16 (submitted through SOLAR).',
  visa_tip = 'Apply for your Student''s Pass at least 2 months before your program starts. The process is largely online through the SOLAR system. Once approved, you''ll receive an In-Principle Approval (IPA) letter to enter Singapore, with the actual pass issued after arrival.',
  
  -- Tuition & Living Costs
  bachelor_fee_public = 'SGD 8,200 - 12,800 per year (subsidized for citizens), SGD 17,550 - 35,000 (international students)',
  bachelor_fee_private = 'SGD 20,000 - 45,000 per year',
  bachelor_fee_medical = 'SGD 28,000 - 135,000 per year',
  master_fee_public = 'SGD 20,000 - 45,000 per year',
  master_fee_private = 'SGD 25,000 - 60,000 per year',
  master_fee_business = 'SGD 40,000 - 80,000 per program',
  accommodation_cost = 'SGD 500 - 2,000 per month',
  accommodation_note = 'University housing costs SGD 300-800/month (shared rooms) to SGD 800-1,500/month (single rooms). Private rentals range from SGD 1,000-3,500/month depending on location and type.',
  food_cost = 'SGD 300 - 800 per month',
  food_note = 'Hawker centers and food courts offer affordable meals (SGD 3-6 per meal). University canteens are similarly priced. Grocery shopping and cooking at home can save money, while restaurant dining costs significantly more.',
  transport_cost = 'SGD 50 - 150 per month',
  transport_note = 'Public transportation is efficient and affordable with student concession cards available. MRT (subway) and buses cover most areas, with typical monthly costs of SGD 50-100 for regular commuting.',
  utilities_cost = 'SGD 150 - 300 per month',
  utilities_note = 'Includes electricity, water, gas, and internet. Air conditioning significantly increases electricity costs. Often included in university accommodation fees.',
  other_cost = 'SGD 200 - 500 per month',
  other_note = 'Includes phone plans (SGD 20-80), books and supplies (SGD 200-500 per semester), personal expenses, and entertainment.',
  total_monthly_cost = 'SGD 1,200 - 3,750 per month',
  budget_tip1 = 'Use student concession cards for public transportation discounts and take advantage of student prices at campus eateries and facilities.',
  budget_tip2 = 'Consider shared housing to reduce accommodation costs, which represent the largest portion of living expenses in Singapore.',
  budget_tip3 = 'Eat at hawker centers and food courts, which offer delicious local cuisine at a fraction of restaurant prices.',
  budget_tip4 = 'Look for student deals and free activities—Singapore offers many free cultural events, parks, and attractions that don''t require spending.',
  government_scholarships = 'Singapore government scholarships include ASEAN Scholarships, Singapore International Graduate Award (SINGA), and ministry-specific scholarships for various fields of study.',
  university_scholarships = 'NUS, NTU, SMU and other institutions offer merit-based scholarships covering partial or full tuition, with some including living allowances for outstanding international students.',
  external_scholarships = 'Private foundations, corporate sponsors, and home country organizations provide additional funding opportunities for international students studying in Singapore.',
  
  -- Student Life
  campus_life = 'Singapore campuses feature state-of-the-art facilities including modern libraries, research centers, sports complexes, and student hubs with comprehensive services for academic and personal support.',
  campus_life_extra = 'Student organizations cover diverse interests from academic and professional development to arts, culture, sports, and community service. Regular events, competitions, and career fairs enhance the vibrant campus experience.',
  work_opportunities = 'International students can work up to 16 hours per week during term time (more during vacations) without additional permits. Post-graduation, students can stay for up to 1 year to seek employment under the Post-Study Work Visa.',
  work_opportunities_extra = 'Singapore''s strong economy offers excellent internship and career opportunities in finance, technology, engineering, healthcare, and other sectors. The city-state''s status as a regional hub attracts multinational corporations actively recruiting international talent.',
  cultural_experience = 'Singapore offers a unique multicultural environment blending Chinese, Malay, Indian, and Western influences. This cultural diversity is reflected in festivals, cuisine, architecture, and daily life throughout the city-state.',
  cultural_experience_extra = 'Despite its small size, Singapore offers diverse experiences from ultramodern city life to natural reserves and cultural enclaves. Its central location makes it an ideal base for exploring Southeast Asia during breaks.',
  student_life_image1 = '/images/placeholders/student-life-1.jpg',
  student_life_image2 = '/images/placeholders/student-life-2.jpg',
  student_life_image3 = '/images/placeholders/student-life-3.jpg',
  student_life_image4 = '/images/placeholders/student-life-4.jpg',
  
  -- Testimonials
  testimonial1_name = 'Ananya Sharma',
  testimonial1_image = '/images/placeholders/testimonial-1.jpg',
  testimonial1_program = 'MSc in Data Science and Machine Learning',
  testimonial1_university = 'National University of Singapore',
  testimonial1_quote = 'The academic rigor at NUS is impressive, and Singapore''s position as a tech hub in Asia means we have access to leading companies for projects and internships. The diversity on campus is amazing—I''ve made friends from every continent! Living in Singapore feels incredibly safe and convenient, though the humidity took some getting used to.',
  testimonial1_country = 'From India',
  testimonial2_name = 'Daniel Kim',
  testimonial2_image = '/images/placeholders/testimonial-2.jpg',
  testimonial2_program = 'Bachelor of Business Management',
  testimonial2_university = 'Singapore Management University',
  testimonial2_quote = 'SMU''s interactive teaching style and small class sizes have been perfect for developing my presentation and leadership skills. The university''s location in the heart of the business district offers incredible networking opportunities. Singapore''s efficiency and cleanliness make it an ideal place to focus on studies while still enjoying a vibrant city life.',
  testimonial2_country = 'From South Korea',
  testimonial3_name = 'Fatima Al-Farsi',
  testimonial3_image = '/images/placeholders/testimonial-3.jpg',
  testimonial3_program = 'PhD in Biomedical Engineering',
  testimonial3_university = 'Nanyang Technological University',
  testimonial3_quote = 'The research facilities at NTU are world-class, and the funding for STEM research is generous. What I appreciate most is the collaborative environment that brings together researchers from different disciplines and cultural backgrounds. Singapore''s strategic location also means we regularly host international conferences with leading researchers.',
  testimonial3_country = 'From Oman',
  
  -- FAQs
  faq1_question = 'What are the benefits of studying in Singapore?',
  faq1_answer = 'Key benefits include world-class education with globally recognized qualifications, English-medium instruction, strategic location in Asia, modern infrastructure and facilities, safe environment, multicultural experience, strong industry connections, excellent career opportunities, and proximity to emerging Asian markets.',
  faq2_question = 'How much does it cost to study and live in Singapore?',
  faq2_answer = 'Tuition fees range from SGD 17,550-45,000 per year for international undergraduate students at public universities (higher for medicine and specialized programs). Living expenses typically amount to SGD 1,200-3,750 per month depending on accommodation type and lifestyle choices.',
  faq3_question = 'What are the work opportunities for international students?',
  faq3_answer = 'During studies, students can work up to 16 hours per week term-time and full-time during vacations without additional permits. After graduation, the Post-Study Work Visa allows graduates to stay and work for up to 1 year, with options to convert to an Employment Pass for longer-term work.',
  faq4_question = 'What are the visa requirements for studying in Singapore?',
  faq4_answer = 'International students need a Student''s Pass, requiring acceptance from a Singapore educational institution, completed application through the SOLAR system, passport validity of at least 6 months, and a medical examination including chest X-ray and HIV test upon arrival.',
  faq5_question = 'Are there scholarships available for international students?',
  faq5_answer = 'Yes, scholarships are available through Singapore government agencies (A*STAR, MOE), individual universities (merit-based tuition reductions), and external organizations. Competition is intense, so early application with strong academic credentials is recommended.',
  faq6_question = 'What is the quality of education in Singapore?',
  faq6_answer = 'Singapore universities consistently rank among the world''s best, with NUS and NTU typically in the global top 20. Education emphasizes rigorous academics, critical thinking, innovation, and practical application, with strong industry connections and research opportunities across disciplines.',
  faq7_question = 'How is student life in Singapore?',
  faq7_answer = 'Student life is vibrant with diverse campus activities, clubs, and events. Singapore offers excellent public transportation, diverse cuisine at all price points, rich cultural experiences, and numerous recreational options. The city is extremely safe with low crime rates and clean, efficient public services.',
  faq8_question = 'What career prospects are available after graduating in Singapore?',
  faq8_answer = 'Singapore''s strong economy offers excellent opportunities in finance, technology, engineering, healthcare, logistics, and other sectors. The government actively attracts talent in emerging fields like fintech, biomedical sciences, and sustainable development, with various programs supporting entrepreneurship and innovation.'
WHERE slug = 'singapore'; 