-- Update data for United States country
UPDATE countries
SET
  -- Basic Information
  capital = 'Washington, D.C.',
  population = '331.9 million (2021)',
  language = 'English',
  currency = 'US Dollar (USD)',
  academic_year = 'August/September to May/June',
  education_system = 'Credit-based semester or quarter system',
  
  -- Education Statistics
  international_students = '1 million+',
  top_universities = '150+ universities in global top 500',
  english_programs = '20,000+ programs taught in English',
  post_study_work = 'Up to 3 years (Optional Practical Training)',
  
  -- Education System
  bachelor_info = 'Usually 4 years. Combines general education courses, major-specific requirements, and electives, offering flexibility to explore different fields before specializing. Liberal arts focus in many programs encourages well-rounded development.',
  master_info = 'Usually 1-2 years. Programs can be course-based, research-based, or a combination, often with strong industry connections and practical components.',
  phd_info = 'Usually 5-7 years. Begins with advanced coursework followed by comprehensive exams and dissertation research. Teaching assistantships are common and provide financial support.',
  teaching_style = 'Interactive and discussion-based approach emphasizing critical thinking, analytical skills, and class participation. Features a mix of lectures, seminars, laboratory work, and group projects.',
  grading_system = 'Based on a 4.0 GPA scale: A (4.0, 90-100%), B (3.0, 80-89%), C (2.0, 70-79%), D (1.0, 60-69%), F (0.0, below 60%). Most graduate programs require maintaining at least a 3.0 GPA.',
  instruction_language = 'English is the primary language of instruction across all institutions and programs.',
  academic_calendar = 'Two main systems: semester (Fall: August-December, Spring: January-May) or quarter (three 10-week terms plus optional summer quarter). Most universities follow the semester system.',
  universities_intro = 'The US has over 4,000 accredited higher education institutions, ranging from large public research universities to small private liberal arts colleges, community colleges, and specialized institutes. Institutions vary widely in size, focus, location, and cost.',
  
  -- Admission & Visa Requirements
  educational_requirements = 'For undergraduate studies, completed secondary education with strong academic performance. For graduate programs, a relevant bachelor''s degree is required, with competitive GPA (typically 3.0/4.0 or higher).',
  transcript_requirements = 'Official transcripts from all previous educational institutions, with certified English translations if originals are not in English. Credential evaluation may be required for international qualifications.',
  entrance_exams = 'For undergraduate: SAT or ACT typically required. For graduate: GRE for most programs, GMAT for business, LSAT for law, or MCAT for medicine. International students may need to submit scores even if exempt in their home country.',
  english_requirements = 'TOEFL: typically 80-100 iBT for undergraduate, 90-100+ for graduate programs. IELTS: 6.5-7.0 overall (minimum 6.0-6.5 in each section). Some universities also accept PTE Academic or Duolingo English Test.',
  language_exemptions = 'Students from countries where English is the primary language of instruction may be exempt from language tests. Some universities may waive requirements for students who have studied in English-medium institutions for specific periods.',
  visa_requirements = 'International students need an F-1 student visa. Must be accepted into a SEVP-certified school, receive an I-20 form, pay the SEVIS fee, and complete a visa interview at a US embassy or consulate.',
  financial_requirements = 'Proof of sufficient funds to cover the entire first year of tuition and living expenses, plus evidence of funding sources for subsequent years. Documentation typically includes bank statements, scholarship letters, or sponsorship guarantees.',
  health_requirements = 'Most universities require proof of immunizations and health insurance coverage. Universities often offer student health insurance plans, but students may purchase private plans that meet minimum requirements.',
  additional_documents = 'Valid passport (valid for at least six months beyond your intended period of stay), DS-160 confirmation, SEVIS fee receipt, passport-sized photographs, and supporting financial documents.',
  visa_tip = 'Apply for your visa as early as possible after receiving your I-20, as processing times vary significantly. During your visa interview, clearly explain your academic plans and ties to your home country, as officers evaluate your intent to return after completing studies.',
  
  -- Tuition & Living Costs
  bachelor_fee_public = 'USD 20,000 - 40,000 per year (in-state), USD 25,000 - 55,000 (out-of-state)',
  bachelor_fee_private = 'USD 30,000 - 60,000 per year',
  bachelor_fee_medical = 'USD 50,000 - 70,000 per year',
  master_fee_public = 'USD 20,000 - 45,000 per year',
  master_fee_private = 'USD 30,000 - 65,000 per year',
  master_fee_business = 'USD 40,000 - 100,000 per program',
  accommodation_cost = 'USD 800 - 1,800 per month',
  accommodation_note = 'On-campus housing costs USD 800-1,200/month including utilities. Off-campus options range from USD 600-1,800/month depending on location and type. Costs are significantly higher in major cities like New York, Boston, and San Francisco.',
  food_cost = 'USD 300 - 600 per month',
  food_note = 'University meal plans cost approximately USD 300-500/month. Grocery shopping amounts to USD 200-400/month for basic necessities. Eating out regularly will increase costs substantially.',
  transport_cost = 'USD 50 - 150 per month',
  transport_note = 'Public transportation costs vary widely by city. Many universities offer free shuttle services around campus and to nearby areas. Some cities offer student discounts on public transport.',
  utilities_cost = 'USD 100 - 200 per month',
  utilities_note = 'Includes electricity, heating/cooling, water, and internet. Often included in on-campus housing fees but additional for off-campus housing.',
  other_cost = 'USD 250 - 500 per month',
  other_note = 'Includes phone plans (USD 50-75), books and supplies (USD 500-1,200 per year), health insurance (USD 1,500-2,500 per year), and personal expenses.',
  total_monthly_cost = 'USD 1,500 - 3,250 per month',
  budget_tip1 = 'Purchase used textbooks or rent them instead of buying new to save hundreds of dollars per semester.',
  budget_tip2 = 'Consider becoming a Resident Assistant (RA) in university housing to receive free or discounted accommodation.',
  budget_tip3 = 'Look for on-campus employment opportunities (up to 20 hours per week), which are convenient and often accommodate student schedules.',
  budget_tip4 = 'Open a US bank account to avoid foreign transaction fees and easily manage payments for rent, utilities, and other expenses.',
  government_scholarships = 'Fulbright Foreign Student Program, Humphrey Fellowship Program, and American government initiatives like USAID provide funding for international students.',
  university_scholarships = 'Many US universities offer merit-based scholarships for international students, covering partial tuition. Athletic scholarships and talent-based awards are also available at many institutions.',
  external_scholarships = 'Various foundations, corporations, and organizations offer scholarships for international students, often targeting specific countries, fields of study, or demographics.',
  
  -- Student Life
  campus_life = 'US campuses typically offer comprehensive facilities including modern libraries, research centers, recreational facilities, student unions, dining halls, and health centers.',
  campus_life_extra = 'Campus life features a wide range of extracurricular activities through student organizations, clubs, fraternities and sororities, volunteering opportunities, and cultural events.',
  work_opportunities = 'International students can work on-campus for up to 20 hours per week during the academic year and full-time during breaks. After the first academic year, off-campus work may be available through Curricular Practical Training (CPT).',
  work_opportunities_extra = 'After graduation, Optional Practical Training (OPT) allows students to work in their field of study for 12 months (extended to 36 months for STEM graduates). Internships and co-op programs are often integrated into degree programs.',
  cultural_experience = 'The US offers tremendous cultural diversity both on and off campus. Each region has distinct characteristics, from the bustling East Coast cities to the West Coast tech hubs, Southern hospitality, and Midwestern charm.',
  cultural_experience_extra = 'Students can experience American traditions through sporting events, holidays, music festivals, and road trips to national parks, while also finding communities that celebrate their own cultural backgrounds.',
  student_life_image1 = '/images/placeholders/student-life-1.jpg',
  student_life_image2 = '/images/placeholders/student-life-2.jpg',
  student_life_image3 = '/images/placeholders/student-life-3.jpg',
  student_life_image4 = '/images/placeholders/student-life-4.jpg',
  
  -- Testimonials
  testimonial1_name = 'Javier Morales',
  testimonial1_image = '/images/placeholders/testimonial-1.jpg',
  testimonial1_program = 'Ph.D. in Computer Science',
  testimonial1_university = 'Stanford University',
  testimonial1_quote = 'The research opportunities in the US are unparalleled. At Stanford, I''ve had access to cutting-edge technology and collaborated with industry leaders in Silicon Valley. The academic environment encourages innovation and interdisciplinary thinking that has transformed my approach to problem-solving.',
  testimonial1_country = 'From Mexico',
  testimonial2_name = 'Aisha Rahman',
  testimonial2_image = '/images/placeholders/testimonial-2.jpg',
  testimonial2_program = 'Bachelor of Arts in International Relations',
  testimonial2_university = 'Georgetown University',
  testimonial2_quote = 'Studying in Washington D.C. has given me incredible exposure to global politics and diplomacy. The classroom discussions are enriched by diverse international perspectives, and I''ve had opportunities to intern at think tanks and attend policy events that wouldn''t be possible elsewhere.',
  testimonial2_country = 'From Bangladesh',
  testimonial3_name = 'Hiroshi Tanaka',
  testimonial3_image = '/images/placeholders/testimonial-3.jpg',
  testimonial3_program = 'MBA',
  testimonial3_university = 'University of Chicago Booth School of Business',
  testimonial3_quote = 'My MBA experience has been transformative. The case-based learning approach, networking opportunities with industry leaders, and diverse cohort have expanded my business perspective. Chicago offers the perfect blend of academic rigor and real-world business exposure.',
  testimonial3_country = 'From Japan',
  
  -- FAQs
  faq1_question = 'What are the benefits of studying in the United States?',
  faq1_answer = 'The US offers world-renowned universities with cutting-edge research facilities, flexible education allowing customization of degrees, diverse campus environments, extensive networking opportunities, strong career connections, practical training options after graduation, and exposure to a multicultural society.',
  faq2_question = 'How much does it cost to study and live in the United States?',
  faq2_answer = 'Tuition ranges from $20,000-60,000+ per year depending on the institution type and program. Living expenses vary widely by location, ranging from $18,000-39,000 annually. Major cities like New York, San Francisco, and Boston have significantly higher costs than smaller towns and midwestern or southern regions.',
  faq3_question = 'What standardized tests do I need to take for admission?',
  faq3_answer = 'For undergraduate studies: SAT or ACT, plus TOEFL/IELTS for non-native English speakers. For graduate programs: GRE (general programs), GMAT (business), LSAT (law), or MCAT (medicine), along with English proficiency tests. Some universities are becoming "test-optional" so check specific requirements.',
  faq4_question = 'Can I work while studying in the United States?',
  faq4_answer = 'F-1 visa students can work on-campus up to 20 hours weekly during terms and full-time during breaks. After completing one academic year, students may qualify for off-campus work through CPT for internships related to their field of study. Off-campus work authorization is limited to specific circumstances.',
  faq5_question = 'What are the visa requirements for studying in the United States?',
  faq5_answer = 'Most international students need an F-1 visa, requiring acceptance to a SEVP-certified school, Form I-20, SEVIS fee payment, proof of sufficient funds, strong ties to home country, and a successful visa interview. The process should be started at least 3-5 months before the program begins.',
  faq6_question = 'Are there scholarships available for international students?',
  faq6_answer = 'Yes, though competition is high. Sources include university-specific scholarships (merit-based, need-based, or diversity scholarships), US government programs (Fulbright), private foundations, and home country funding. Most financial aid for international students is merit-based rather than need-based.',
  faq7_question = 'How do I choose the right university in the United States?',
  faq7_answer = 'Consider program quality and rankings in your field of interest, location (urban vs. rural, climate, cost of living), campus size and culture, available support services for international students, internship opportunities, financial considerations, and post-graduation outcomes. Visit campuses virtually or in-person if possible.',
  faq8_question = 'What are the post-graduation work opportunities in the United States?',
  faq8_answer = 'After graduation, F-1 students can apply for Optional Practical Training (OPT) allowing work in their field of study for 12 months (extendable to 36 months for STEM graduates). Afterwards, many pursue H-1B work visas sponsored by employers, with possible pathways to permanent residency depending on circumstances.'
WHERE slug = 'usa'; 