name: Dead Link Checker

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'

      - name: Create maintenance label
        uses: actions/github-script@v6.4.1
        continue-on-error: true
        with:
          script: |
            try {
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'maintenance',
                color: 'fbca04',
                description: 'Maintenance tasks and updates'
              });
              console.log('Label created or already exists');
            } catch (error) {
              console.log('Error creating label:', error.message);
            }

      - name: Install broken-link-checker
        run: npm install -g broken-link-checker

      - name: Determine base URL
        id: url
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "base_url=https://qogent.in" >> $GITHUB_OUTPUT
          else
            echo "base_url=http://localhost:3000" >> $GITHUB_OUTPUT
          fi

      - name: Check for dead links
        id: blc
        run: |
          echo "Starting link check for ${{ steps.url.outputs.base_url }}"
          npx blc ${{ steps.url.outputs.base_url }} --follow --recursive --ordered --filter-level 3 --exclude "^(tel:|mailto:|sms:|#)" > dead-links-report.txt || true
          
          # Initialize counters
          total_links=0
          broken_links=0
          excluded_links=0
          
          # Count links using proper string handling
          while IFS= read -r line; do
            if [[ $line == *"Getting links from"* ]] || [[ $line == *"├"* ]]; then
              ((total_links++))
            fi
            if [[ $line == *"BROKEN"* ]]; then
              ((broken_links++))
            fi
            if [[ $line == *"excluded"* ]]; then
              ((excluded_links++))
            fi
          done < dead-links-report.txt
          
          # Set outputs using proper syntax
          echo "total_links=${total_links}" >> $GITHUB_OUTPUT
          echo "broken_links=${broken_links}" >> $GITHUB_OUTPUT
          echo "excluded_links=${excluded_links}" >> $GITHUB_OUTPUT
          
          # Also set environment variables for use in subsequent steps
          echo "TOTAL_LINKS=${total_links}" >> $GITHUB_ENV
          echo "BROKEN_LINKS=${broken_links}" >> $GITHUB_ENV
          echo "EXCLUDED_LINKS=${excluded_links}" >> $GITHUB_ENV

      - name: Create issue if broken links found
        if: steps.blc.outputs.broken_links != '0'
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('dead-links-report.txt', 'utf8');
            
            const summary = `# Dead Links Report
            
            ## Summary
            - Total Links Scanned: ${{ steps.blc.outputs.total_links }}
            - Broken Links Found: ${{ steps.blc.outputs.broken_links }}
            - Links Excluded: ${{ steps.blc.outputs.excluded_links }}
            
            ## Full Report
            \`\`\`
            ${report}
            \`\`\`
            
            ## Next Steps
            1. Review and fix broken links
            2. Update any outdated external references
            3. Verify all internal page links
            
            Please review and fix these issues to maintain site reliability.`;
            
            const issueParams = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🔍 Dead Links Found: ${process.env.BROKEN_LINKS} broken links detected`,
              body: summary,
              labels: ['maintenance']
            };
            
            await github.rest.issues.create(issueParams);

      - name: Upload dead links report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dead-links-report
          path: dead-links-report.txt
          retention-days: 30