name: Dead Link Checker

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'

      - name: Create maintenance label
        uses: actions/github-script@v6.4.1
        continue-on-error: true
        with:
          script: |
            try {
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'maintenance',
                color: 'fbca04',
                description: 'Maintenance tasks and updates'
              });
              console.log('Label created or already exists');
            } catch (error) {
              console.log('Error creating label:', error.message);
            }

      - name: Install broken-link-checker
        run: npm install -g broken-link-checker

      - name: Determine base URL
        id: url
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "BASE_URL=https://qogent.in" >> $GITHUB_ENV
          else
            echo "BASE_URL=http://localhost:3000" >> $GITHUB_ENV
          fi

      - name: Check for dead links
        id: blc
        run: |
          echo "Starting link check for ${{ env.BASE_URL }}"
          npx blc ${{ env.BASE_URL }} --follow --recursive --ordered --filter-level 3 --exclude "^(tel:|mailto:|sms:|#)" > dead-links-report.txt || true
          
          # Count total and broken links
          TOTAL_LINKS=$(grep -c "Getting links from\|├" dead-links-report.txt || echo "0")
          BROKEN_LINKS=$(grep -c "BROKEN" dead-links-report.txt || echo "0")
          EXCLUDED_LINKS=$(grep -c "excluded" dead-links-report.txt || echo "0")
          
          echo "TOTAL_LINKS=$TOTAL_LINKS" >> $GITHUB_ENV
          echo "BROKEN_LINKS=$BROKEN_LINKS" >> $GITHUB_ENV
          echo "EXCLUDED_LINKS=$EXCLUDED_LINKS" >> $GITHUB_ENV

      - name: Create issue if broken links found
        if: env.BROKEN_LINKS != '0'
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('dead-links-report.txt', 'utf8');
            
            try {
              const summary = `# Dead Links Report
              
              ## Summary
              - Total Links Scanned: ${{ env.TOTAL_LINKS }}
              - Broken Links Found: ${{ env.BROKEN_LINKS }}
              - Links Excluded: ${{ env.EXCLUDED_LINKS }}
              
              ## Known Issues
              1. Missing Pages (404):
                 - /get-started
                 - /success-stories
                 - /contact
                 - /services
              
              2. External Links:
                 - Indeed job boards (403)
                 - IELTS sample test questions
                 - Blog posts with incorrect domains
              
              ## Full Report
              \`\`\`
              ${report}
              \`\`\`
              
              ## Next Steps
              1. Create missing pages
              2. Update external links to use alternative job boards
              3. Fix blog post URLs to use correct domain
              4. Review and update IELTS resource links
              
              Please review and fix these issues to maintain site reliability.`;
              
              const issueParams = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `🔍 Dead Links Found: ${process.env.BROKEN_LINKS} broken links detected`,
                body: summary,
                labels: ['maintenance']
              };
              
              await github.rest.issues.create(issueParams);
            } catch (error) {
              console.log('Error creating issue:', error.message);
              core.setFailed('Failed to create issue');
            }

      - name: Upload dead links report
        uses: actions/upload-artifact@v2.3.1
        with:
          name: dead-links-report
          path: dead-links-report.txt
          retention-days: 30