name: Performance Monitoring

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - 'src/**'

env:
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      
    steps:
      - uses: actions/checkout@v3.5.3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: |
          pnpm install
          npm install -g @lhci/cli@0.12.x
          
      - name: Build application
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: pnpm build
        
      - name: Start Next.js server
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          pnpm start &
          echo "Waiting for Next.js server to be ready..."
          
          # Wait for server to be ready with timeout
          timeout=60
          while ! curl -s http://localhost:3000 > /dev/null; do
            if [ $timeout -le 0 ]; then
              echo "Timeout waiting for server to start"
              exit 1
            fi
            echo "Waiting for server... ($timeout seconds remaining)"
            sleep 5
            timeout=$((timeout - 5))
          done
          
          echo "Server is ready!"
          
      - name: Run Lighthouse CI
        run: |
          echo "Starting Lighthouse CI..."
          mkdir -p .lighthouseci
          
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            BASE_URL="https://qogent.in"
          else
            BASE_URL="http://localhost:3000"
          fi
          
          echo "Testing URL: $BASE_URL"
          
          # Test if the server is responding
          curl -v $BASE_URL
          
          # Run Lighthouse CI with verbose logging and explicit output directory
          lhci collect --verbose --url=$BASE_URL --config=.github/lighthouse-config.json --outputDir=.lighthouseci
          
          # List contents after collection
          echo "Contents of .lighthouseci after collection:"
          ls -la .lighthouseci/
          
          lhci assert --config=.github/lighthouse-config.json
        continue-on-error: true
        id: lighthouse
        
      - name: Debug Lighthouse output
        if: always()
        run: |
          echo "Checking .lighthouseci directory contents:"
          ls -la .lighthouseci/
          
          # Print Lighthouse logs if they exist
          if [ -d ".lighthouseci" ]; then
            echo "Lighthouse logs:"
            find .lighthouseci -type f -name "*.log" -exec cat {} \;
            echo "Lighthouse reports:"
            find .lighthouseci -type f -name "*.json" -exec cat {} \;
          fi
          
      - name: Format Lighthouse Score
        id: format-score
        if: always()
        run: |
          REPORT_PATH=$(find .lighthouseci -name "*.json" | head -n 1)
          if [ ! -f "$REPORT_PATH" ]; then
            echo "No Lighthouse report found in directory:"
            ls -la .lighthouseci/
            pwd
            find . -name "*.json"
            exit 1
          fi
          
          echo "Found report at: $REPORT_PATH"
          echo "Report contents:"
          cat "$REPORT_PATH"
          
          echo "PERFORMANCE_SCORE=$(jq '.categories.performance.score' $REPORT_PATH)" >> $GITHUB_ENV
          echo "ACCESSIBILITY_SCORE=$(jq '.categories.accessibility.score' $REPORT_PATH)" >> $GITHUB_ENV
          echo "SEO_SCORE=$(jq '.categories.seo.score' $REPORT_PATH)" >> $GITHUB_ENV
          echo "BEST_PRACTICES_SCORE=$(jq '.categories.["best-practices"].score' $REPORT_PATH)" >> $GITHUB_ENV
          
      - name: Store Lighthouse report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: |
            .lighthouseci
            .lighthouseci/*.json
            .lighthouseci/*.html
            .lighthouseci/*.log
          retention-days: 30
          
      - name: Create Issue on Low Scores
        if: success() && (env.PERFORMANCE_SCORE < 0.9 || env.ACCESSIBILITY_SCORE < 0.9 || env.SEO_SCORE < 0.9 || env.BEST_PRACTICES_SCORE < 0.9)
        uses: actions/github-script@v6.4.1
        with:
          script: |
            try {
              const scores = {
                Performance: (process.env.PERFORMANCE_SCORE * 100).toFixed(1),
                Accessibility: (process.env.ACCESSIBILITY_SCORE * 100).toFixed(1),
                SEO: (process.env.SEO_SCORE * 100).toFixed(1),
                'Best Practices': (process.env.BEST_PRACTICES_SCORE * 100).toFixed(1)
              };
              
              const lowScores = Object.entries(scores)
                .filter(([_, score]) => score < 90)
                .map(([category, score]) => `- ${category}: ${score}%`)
                .join('\n');
              
              const issue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🚨 Lighthouse Performance Alert',
                body: `## Performance Monitoring Alert
                
                The following scores are below the 90% threshold:
                
                ${lowScores}
                
                ### All Scores:
                - Performance: ${scores.Performance}%
                - Accessibility: ${scores.Accessibility}%
                - SEO: ${scores.SEO}%
                - Best Practices: ${scores['Best Practices']}%
                
                ### Next Steps
                1. Review the detailed report in the workflow artifacts
                2. Focus on improving the low-scoring areas
                3. Consider running Lighthouse locally to test improvements
                
                [View detailed report](${process.env.GITHUB_SERVER_URL}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`,
                labels: ['performance']
              });
            } catch (error) {
              console.log('Error creating issue:', error.message);
              core.setFailed('Failed to create performance issue');
            } 